# Supabase project configuration
# Dokumentation: https://supabase.com/docs/guides/local-development

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
site_url = "http://localhost:3000"

[analytics]
enabled = false