/**
 * getTaxonomy
 * ===========
 * Kanonische Taxonomie-Quelle für Frontend und Backend.
 *
 * ARCHITEKTUR:
 * - TaxonomyEntry Entitäten in der Datenbank sind die EINZIGE Wahrheitsquelle.
 * - Frontend ruft diese Function auf → kein statisches Inline-Preset mehr nötig.
 * - startResearchRun ruft diese Function auf → bettet Taxonomie in search_plan_json ein.
 * - processResearchRun liest Taxonomie aus search_plan_json → kein DB-Call im Batch-Loop.
 *
 * HASH-SYSTEM:
 * - Jeder Eintrag hat einen content_hash (SHA-256 der relevanten Felder).
 * - taxonomy_hash im ResearchRun = Hash aller aktiven Einträge → vollständige Rückverfolgung.
 *
 * FALLBACK:
 * - Wenn DB leer → eingebetteter SEED wird verwendet + in DB geschrieben.
 * - Dadurch ist die Function beim ersten Aufruf selbst-initialisierend.
 */

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// ── SEED-Daten: Kanonische Taxonomie (wird beim ersten Aufruf in DB geschrieben) ──
// Dies ist die EINZIGE inhaltliche Quelle. Frontend + Backend lesen aus der DB.
// Änderungen hier → nächster Aufruf schreibt sie in die DB (wenn Einträge fehlen).
const TAXONOMY_SEED = [
  {industry_id:"gebaeudereinigung",label:"Gebäudereinigung",sort_order:1,own_services:["Büroreinigung","Treppenhausreinigung","Praxisreinigung","Fensterreinigung","Grundreinigung","Baureinigung","Sonderreinigung","Hausmeisterdienst","Winterdienst","Teppichreinigung","Glasreinigung"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Bürogebäude","Arztpraxen","Zahnarztpraxen","Ärztehäuser","Kitas","Schulen","Pflegeheime","Seniorenheime","Hotels","Autohäuser","Fitnessstudios","Gewerbehallen","Industriebetriebe","Einzelhandel","Supermärkte"],excluded_customer_types:["Privathaushalte","Einmalige Kleinstaufträge","private Wohnungen","Kleinanzeigen","Jobangebote"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Bürogebäude","Ärztehaus","Arztpraxis","Zahnarztpraxis","Kindertagesstätte","Schule","Pflegeheim","Seniorenheim","Hotel","Autohaus","Fitnessstudio","Gewerbepark","Industrieunternehmen","Einzelhandel","Supermarkt"],search_keyword_variants:{"Hausverwaltung":["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Mietverwaltung"],"Arztpraxis":["Arztpraxis","Ärztehaus","Zahnarztpraxis","Medizinisches Versorgungszentrum"],"Pflegeheim":["Pflegeheim","Seniorenheim","Seniorenresidenz","Altenheim"],"Hotel":["Hotel","Gasthof","Pension"],"Gewerbe":["Gewerbepark","Bürogebäude","Industrieunternehmen","Gewerbehalle"],"Schule":["Schule","Gymnasium","Grundschule","Berufsschule"],"Kita":["Kindertagesstätte","Kita","Kindergarten","Krippe"]},negative_keywords:["privat","job","karriere","ausbildung","stellenangebot","minijob","kleinanzeigen","wohnung gesucht","mietgesuch"],bad_fit_signals:["privat","job","karriere","kleinanzeige","einzelperson","mietgesuch","gesucht","ausbildung"],scoring_signals:["verwaltung","gewerbe","praxis","hotel","pflege","industrie","facility","büro","objekt","standort","wohnanlage","immobilien"],query_priority:["Hausverwaltung","Immobilienverwaltung","Pflegeheim","Arztpraxis","Hotel","Bürogebäude","Schule","Kita"],ideal_customer_profiles:["regelmäßiger Reinigungsbedarf","mehrere Standorte","größere Nutzfläche","laufende Objektbetreuung"],google_place_types:["property_management_company","doctor","dentist","hospital","lodging","car_dealer","gym","school"]},
  {industry_id:"sicherheitsdienst",label:"Sicherheitsdienst",sort_order:2,own_services:["Objektschutz","Baustellenbewachung","Veranstaltungsschutz","Doorman-Service","Revierdienst","Alarmverfolgung","Werkschutz","Empfangsdienst","Parkplatzüberwachung"],target_customer_types:["Baustellen","Bauunternehmen","Logistikzentren","Industriebetriebe","Veranstalter","Hotels","Einkaufszentren","Parkhäuser","Messeveranstalter","Eventlocations","Gewerbeparks","Einzelhandel","Wohnanlagen"],excluded_customer_types:["Privatpersonen","kleine Privatfeiern","Vereine ohne Budget","Jobsuchende"],searchable_business_categories:["Bauunternehmen","Logistikzentrum","Industrieunternehmen","Veranstalter","Eventlocation","Hotel","Einkaufszentrum","Parkhaus","Messeveranstalter","Gewerbepark","Einzelhandel","Facility Management"],search_keyword_variants:{"Baustelle":["Bauunternehmen","Bauträger","Baustelle","Generalunternehmer"],"Event":["Eventlocation","Veranstalter","Messeveranstalter","Kongresszentrum"],"Industrie":["Industriebetrieb","Gewerbepark","Logistikzentrum","Produktionsbetrieb"],"Hotel":["Hotel","Tagungshotel","Kongresshotel"],"Einzelhandel":["Einkaufszentrum","Shopping Center","Einzelhandel"]},negative_keywords:["job","stellenangebot","ausbildung","security job","privat","ehrenamt","karriere","bewerber"],bad_fit_signals:["job","karriere","privat","ehrenamt","verein klein","ausbildung","bewerber"],scoring_signals:["objektschutz","baustelle","logistik","industrie","veranstaltung","zugang","werkschutz","publikumsverkehr","gewerbe","lager","messe"],query_priority:["Bauunternehmen","Logistikzentrum","Industrieunternehmen","Hotel","Eventlocation","Einkaufszentrum"],ideal_customer_profiles:["hoher Sicherheitsbedarf","Publikumsverkehr","wertvolle Güter","Nachtbetrieb"],google_place_types:["shopping_mall","lodging","event_venue","stadium","parking","storage"]},
  {industry_id:"it_service",label:"IT-Service",sort_order:3,own_services:["IT-Support","Managed Services","Serverbetreuung","Netzwerkbetreuung","Microsoft 365","Cybersecurity","Cloud-Lösungen","Backup","Telefonanlage","Hardware-Service"],target_customer_types:["Arztpraxen","Zahnarztpraxen","Steuerberater","Kanzleien","KMU","Schulen","Pflegeeinrichtungen","Handwerksbetriebe","Büros","Einzelhandel","Immobilienverwaltungen","Logistikunternehmen"],excluded_customer_types:["Privatpersonen","Gaming-PC-Anfragen","Einmalige Kleinreparaturen","Jobsuchende"],searchable_business_categories:["Arztpraxis","Zahnarztpraxis","Steuerberater","Rechtsanwalt","Kanzlei","Pflegeheim","Schule","Handwerksbetrieb","Büro","Einzelhandel","Immobilienverwaltung","Logistikunternehmen","Unternehmensberatung","Ingenieurbüro"],search_keyword_variants:{"Praxen":["Arztpraxis","Zahnarztpraxis","Ärztehaus","Medizinisches Versorgungszentrum"],"Kanzleien":["Rechtsanwalt","Kanzlei","Anwaltskanzlei","Steuerberater","Steuerberatung"],"KMU":["Handwerksbetrieb","Unternehmensberatung","Ingenieurbüro","Bürogebäude"],"Bildung":["Schule","Gymnasium","Bildungszentrum"],"Pflege":["Pflegeheim","Seniorenheim","Reha Zentrum"]},negative_keywords:["privat","gaming","job","karriere","ausbildung","computerhilfe privat","forum","blog"],bad_fit_signals:["privat","gaming","job","forum","einzelperson","haushaltsgerät","reparatur privat"],scoring_signals:["praxis","kanzlei","steuer","pflege","schule","verwaltung","daten","büro","handwerk","logistik"],query_priority:["Arztpraxis","Zahnarztpraxis","Steuerberater","Rechtsanwalt","Handwerksbetrieb","Pflegeheim","Schule"],ideal_customer_profiles:["mehrere Arbeitsplätze","regelmäßiger IT-Bedarf","sensible Daten","Compliance-Anforderungen"],google_place_types:["doctor","dentist","lawyer","accounting","school","hospital"]},
  {industry_id:"gartenbau",label:"Gartenbau",sort_order:4,own_services:["Gartenpflege","Grünanlagenpflege","Rasenpflege","Heckenschnitt","Baumpflege","Winterdienst","Außenanlagenpflege","Pflasterarbeiten","Objektpflege"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Wohnanlagen","Hotels","Gewerbeparks","Kommunen","Pflegeheime","Kitas","Schulen","Facility Management Firmen","Bürogebäude","Industriebetriebe"],excluded_customer_types:["Privatgärten","Einmalige Kleinstaufträge","Kleinanzeigen","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Wohnanlage","Hotel","Gewerbepark","Pflegeheim","Kindertagesstätte","Schule","Facility Management","Bürogebäude","Industrieunternehmen","Friedhof"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnanlage","WEG Verwaltung"],"Gewerbe":["Gewerbepark","Bürogebäude","Industriebetrieb"],"Sozial":["Pflegeheim","Kita","Schule","Altenheim"],"Hotel":["Hotel","Tagungshotel","Gasthof"]},negative_keywords:["privatgarten","privat","job","karriere","kleinanzeigen","gratis","selber machen"],bad_fit_signals:["privat","kleinanzeige","job","einzelgarten","hobby","selbst"],scoring_signals:["anlage","grünfläche","verwaltung","wohnanlage","gewerbe","hotel","pflege","objekt","außenanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","Hotel","Pflegeheim","Gewerbepark","Schule","Kita"],ideal_customer_profiles:["regelmäßige Außenpflege","größere Grünflächen","Wohnanlagenbestand"],google_place_types:["property_management_company","lodging","school","hospital"]},
  {industry_id:"catering",label:"Catering",sort_order:5,own_services:["Business Catering","Event Catering","Messe Catering","Kita Catering","Schulverpflegung","Kantinenservice","Fingerfood","Buffet","Tagungsverpflegung"],target_customer_types:["Eventlocations","Tagungshotels","Seminarzentren","Messeveranstalter","Kongresszentren","Unternehmen","Bürokomplexe","Kitas","Schulen","Pflegeheime","Hotels","Coworking Spaces"],excluded_customer_types:["Privatfeiern","Hochzeiten privat","Geburtstage privat","Kleinanzeigen"],searchable_business_categories:["Eventlocation","Tagungshotel","Seminarzentrum","Messeveranstalter","Kongresszentrum","Bürogebäude","Kindertagesstätte","Schule","Pflegeheim","Hotel","Coworking Space","Veranstalter","Unternehmensberatung"],search_keyword_variants:{"Event":["Eventlocation","Veranstalter","Messeveranstalter","Kongresszentrum","Eventhalle"],"Business":["Bürogebäude","Unternehmensberatung","Coworking Space","Business Center"],"Bildung":["Kindertagesstätte","Schule","Seminarzentrum","Bildungszentrum"],"Hotel":["Tagungshotel","Kongresshotel","Hotel"]},negative_keywords:["privat","hochzeit","geburtstag","familienfeier","job","karriere","kleinanzeigen","selbst kochen"],bad_fit_signals:["privat","hochzeit","geburtstag","kleinanzeige","familienfeier","selbst"],scoring_signals:["event","tagung","messe","seminar","unternehmen","büro","kita","schule","hotel","kongress","veranstaltung"],query_priority:["Eventlocation","Tagungshotel","Kongresszentrum","Seminarzentrum","Bürogebäude","Kita","Schule"],ideal_customer_profiles:["regelmäßige Veranstaltungen","viele Mitarbeitende","Tagungsbetrieb"],google_place_types:["event_venue","lodging","school","conference_center"]},
  {industry_id:"handwerk",label:"Handwerk",sort_order:6,own_services:["Reparaturen","Instandhaltung","Renovierung","Montage","Wartung","Notdienst","Objektbetreuung","Kleinreparaturen"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Bauunternehmen","Gewerbeimmobilienverwaltungen","Facility Management Firmen","Hotels","Praxen","Bürogebäude","Einzelhandel","Wohnungsbaugesellschaften"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen ohne Budget","DIY-Anfragen","Jobangebote"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Bauunternehmen","Facility Management","Hotel","Arztpraxis","Bürogebäude","Einzelhandel","Wohnungsbaugesellschaft","Gewerbeimmobilienverwaltung"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft","WEG Verwaltung"],"Gewerbe":["Bürogebäude","Einzelhandel","Hotel","Gewerbepark"],"Bau":["Bauunternehmen","Facility Management","Generalunternehmer"]},negative_keywords:["privat","selber machen","diy","job","ausbildung","karriere","kleinanzeigen","forum"],bad_fit_signals:["privat","diy","job","kleinanzeige","selbst"],scoring_signals:["verwaltung","objekt","instandhaltung","gewerbe","hotel","bau","facility","wohnanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","Bauunternehmen","Hotel","Bürogebäude","Einzelhandel"],ideal_customer_profiles:["regelmäßiger Instandhaltungsbedarf","mehrere Objekte","Objektbestand"],google_place_types:["property_management_company","lodging","real_estate_agency"]},
  {industry_id:"spedition_logistik",label:"Spedition / Logistik",sort_order:7,own_services:["Transport","Kurierdienst","Expresslieferung","Stückgut","Palettentransport","Möbeltransport","Lagerlogistik","Auslieferung","Same-Day Delivery"],target_customer_types:["Online-Shops","Großhändler","Produktionsbetriebe","Industriebetriebe","Möbelhäuser","Baustoffhändler","Maschinenbauunternehmen","Lebensmittelgroßhandel","Eventfirmen","Einzelhandel","E-Commerce-Unternehmen"],excluded_customer_types:["Privatumzüge","Einzelne Privattransporte","Kleinanzeigen","Jobs"],searchable_business_categories:["Großhandel","Produktionsbetrieb","Industrieunternehmen","Möbelhaus","Baustoffhandel","Maschinenbau","Lebensmittelgroßhandel","Eventagentur","Einzelhandel","Versandhandel","Handelsunternehmen","Küchenstudio"],search_keyword_variants:{"E-Commerce":["Versandhandel","Online Händler","Handelsunternehmen"],"Industrie":["Produktionsbetrieb","Industrieunternehmen","Maschinenbau"],"Handel":["Großhandel","Möbelhaus","Baustoffhandel","Lebensmittelgroßhandel"],"Event":["Eventagentur","Messeveranstalter","Veranstaltungstechnik"]},negative_keywords:["privat","umzug privat","job","fahrer gesucht","karriere","kleinanzeigen","führerschein"],bad_fit_signals:["privat","job","kleinanzeige","einzeltransport","möbel privat"],scoring_signals:["versand","logistik","lager","großhandel","produktion","lieferung","handel","import","export"],query_priority:["Großhandel","Produktionsbetrieb","Industrieunternehmen","Möbelhaus","Maschinenbau","Baustoffhandel"],ideal_customer_profiles:["regelmäßiger Versand","wiederkehrende Transporte","hohes Sendungsvolumen"],google_place_types:["storage","moving_company","wholesale_store"]},
  {industry_id:"gesundheit_medizin",label:"Gesundheit / Medizin",sort_order:8,own_services:["medizinische Dienstleistung","Therapie","Pflegebezogene Dienstleistung","Praxisservice","Gesundheitsberatung","Betriebliches Gesundheitsmanagement"],target_customer_types:["Arztpraxen","Zahnarztpraxen","Therapiezentren","Pflegeheime","Seniorenheime","Apotheken","Reha-Zentren","Privatkliniken","Gesundheitszentren","Physiotherapien","Ergotherapien"],excluded_customer_types:["Privatpersonen","Foren","Selbsthilfegruppen ohne Budget","Jobanzeigen"],searchable_business_categories:["Arztpraxis","Zahnarztpraxis","Therapiezentrum","Pflegeheim","Seniorenheim","Apotheke","Reha Zentrum","Privatklinik","Gesundheitszentrum","Physiotherapie","Ergotherapie","Ärztehaus"],search_keyword_variants:{"Praxis":["Arztpraxis","Zahnarztpraxis","Ärztehaus","Medizinisches Versorgungszentrum"],"Therapie":["Physiotherapie","Ergotherapie","Therapiezentrum","Logopädie"],"Pflege":["Pflegeheim","Seniorenheim","Reha Zentrum","Klinik"]},negative_keywords:["privat","forum","job","karriere","ausbildung","krankheit erfahrung","selbsthilfe","blog"],bad_fit_signals:["forum","privat","job","erfahrung","selbsthilfe","blog"],scoring_signals:["praxis","gesundheit","pflege","therapie","reha","klinik","zentrum","apotheke","medizin"],query_priority:["Arztpraxis","Zahnarztpraxis","Pflegeheim","Physiotherapie","Therapiezentrum","Ärztehaus"],ideal_customer_profiles:["professioneller Gesundheitsbetrieb","regelmäßiger Bedarf","Patientenverkehr"],google_place_types:["doctor","dentist","hospital","pharmacy","physiotherapist","health"]},
  {industry_id:"immobilien",label:"Immobilien",sort_order:9,own_services:["Vermietung","Verwaltung","Verkauf","Gewerbeimmobilien","Projektentwicklung","Immobilienberatung","Standortvermittlung"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","WEG-Verwaltungen","Bauträger","Projektentwickler","Wohnungsbaugesellschaften","Gewerbeimmobilienverwaltungen","Immobiliengesellschaften","Property Management Firmen"],excluded_customer_types:["Privathaushalte","private Vermieter","Ferienwohnung privat","Wohnung gesucht","Mietgesuch"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Bauträger","Projektentwickler","Wohnungsbaugesellschaft","Immobiliengesellschaft","Gewerbeimmobilienverwaltung","Property Management","Facility Management Immobilien","Mietverwaltung"],search_keyword_variants:{"Hausverwaltung":["Hausverwaltung","WEG Verwaltung","Immobilienverwaltung","Mietverwaltung","Objektverwaltung"],"Bauträger":["Bauträger","Wohnbaugesellschaft","Projektentwickler Immobilien","Immobilienprojektentwicklung"],"Gewerbe":["Gewerbeimmobilienverwaltung","Property Management","Facility Management Immobilien"]},negative_keywords:["privat","wohnung gesucht","mietgesuch","ferienwohnung","airbnb","job","karriere","vermiete privat","suche wohnung"],bad_fit_signals:["privat","mietgesuch","wohnung gesucht","ferienwohnung","job","airbnb"],scoring_signals:["verwaltung","weg","gewerbeimmobilien","bestand","objektverwaltung","property management","projektentwicklung","bauträger","wohnanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Bauträger","Wohnungsbaugesellschaft","Property Management"],ideal_customer_profiles:["Eigentümer","Investoren","Bestandshalter","Objektbestand"],google_place_types:["property_management_company","real_estate_agency"]},
  {industry_id:"lager_fulfillment",label:"Lager / Fulfillment",sort_order:10,own_services:["Fulfillment","Lagerung","Kommissionierung","Versandabwicklung","Retourenmanagement","E-Commerce Logistik","Pick & Pack","B2B-Lagerlogistik"],target_customer_types:["Online-Shops","Shopify-Händler","Amazon-Händler","Großhändler","E-Commerce-Unternehmen","Kosmetikmarken","Lebensmittelmarken","Textilhändler","Ersatzteilhändler","Importeure","Startups mit Versand"],excluded_customer_types:["Privatverkäufer","Kleinanzeigen","Dropshipping ohne Bestand","Jobs"],searchable_business_categories:["Versandhandel","Großhandel","Kosmetikmarke","Lebensmittelhersteller","Textilhandel","Ersatzteilhandel","Importeur","Handelsunternehmen","Modehändler","Online Händler"],search_keyword_variants:{"E-Commerce":["Versandhandel","Online Händler","Handelsunternehmen"],"Handel":["Großhandel","Importeur","Textilhandel","Modehändler"],"Produkte":["Kosmetikmarke","Lebensmittelhersteller","Ersatzteilhandel"]},negative_keywords:["privat","kleinanzeigen","job","karriere","ausbildung","ebay privat","zu verschenken"],bad_fit_signals:["privat","kleinanzeige","job","kein bestand","zu verschenken"],scoring_signals:["shop","versand","handel","import","retouren","lager","ecommerce","online"],query_priority:["Großhandel","Versandhandel","Importeur","Handelsunternehmen","Textilhandel"],ideal_customer_profiles:["regelmäßiger Versand","wachsender Onlinehandel","Retourenbedarf"],google_place_types:["storage","wholesale_store"]},
  {industry_id:"facility_service",label:"Facility Service",sort_order:11,own_services:["Hausmeisterdienst","Objektbetreuung","Gebäudemanagement","Technische Betreuung","Reinigung","Winterdienst","Grünpflege","Kleinreparaturen","Kontrolldienste"],target_customer_types:["Hausverwaltungen","Gewerbeimmobilien","Bürogebäude","Hotels","Pflegeheime","Industriebetriebe","Schulen","Kitas","Kommunen","Wohnanlagen"],excluded_customer_types:["Privathaushalte","Einmalige Kleinstaufträge","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Gewerbeimmobilie","Bürogebäude","Hotel","Pflegeheim","Industrieunternehmen","Schule","Kindertagesstätte","Wohnanlage","Gewerbepark"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnanlage","WEG Verwaltung"],"Gewerbe":["Bürogebäude","Gewerbeimmobilie","Industrieunternehmen","Gewerbepark"],"Sozial":["Pflegeheim","Schule","Kita","Altenheim"]},negative_keywords:["privat","job","karriere","ausbildung","kleinanzeigen"],bad_fit_signals:["privat","job","kleinanzeige","einzelperson"],scoring_signals:["objekt","verwaltung","gewerbe","facility","wohnanlage","technisch","gebäude","standort"],query_priority:["Hausverwaltung","Immobilienverwaltung","Bürogebäude","Hotel","Pflegeheim","Gewerbepark"],ideal_customer_profiles:["mehrere Objekte","laufender Objektbedarf","technische Betreuung"],google_place_types:["property_management_company","lodging","school"]},
  {industry_id:"entruempelung",label:"Entrümpelung",sort_order:12,own_services:["Entrümpelung","Haushaltsauflösung","Wohnungsauflösung","Nachlassauflösung","Kellerentrümpelung","Gewerbeauflösung","Messie-Wohnung","Entsorgung","Räumung"],target_customer_types:["Hausverwaltungen","Nachlassverwalter","Betreuungsbüros","Immobilienmakler","Wohnungsbaugesellschaften","Pflegeheime","Seniorenheime","Rechtsanwälte Erbrecht","Sozialdienste","Gerichtliche Betreuer"],excluded_customer_types:["Privathaushalte mit Kleinstauftrag","Sperrmüll Einzelstück","Kleinanzeigen","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Nachlassverwaltung","Betreuungsbüro","Immobilienmakler","Wohnungsbaugesellschaft","Pflegeheim","Seniorenheim","Rechtsanwalt Erbrecht","Sozialdienst"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Nachlass":["Nachlassverwaltung","Rechtsanwalt Erbrecht","Betreuungsbüro","Nachlassverwalter"],"Sozial":["Sozialdienst","Pflegeheim","Seniorenheim","Sozialstation"]},negative_keywords:["privat","sperrmüll kostenlos","kleinanzeigen","job","karriere","zu verschenken"],bad_fit_signals:["privat","kleinanzeige","zu verschenken","job","sperrmüll kostenlos"],scoring_signals:["verwaltung","nachlass","betreuung","erbrecht","wohnung","pflege","sozialdienst","objekt"],query_priority:["Hausverwaltung","Immobilienverwaltung","Sozialdienst","Pflegeheim","Betreuungsbüro","Rechtsanwalt Erbrecht"],ideal_customer_profiles:["regelmäßige Wohnungswechsel","Nachlassfälle","Erbfälle"],google_place_types:["property_management_company","lawyer"]},
  {industry_id:"maler_renovierung",label:"Maler / Renovierung",sort_order:13,own_services:["Malerarbeiten","Renovierung","Tapezieren","Lackieren","Fassadenanstrich","Innenausbau","Wohnungsrenovierung","Gewerberenovierung","Trockenbau"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Hotels","Bürogebäude","Praxen","Einzelhandel","Wohnungsbaugesellschaften","Bauunternehmen","Facility Management Firmen"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen","DIY-Anfragen","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Hotel","Bürogebäude","Arztpraxis","Einzelhandel","Wohnungsbaugesellschaft","Bauunternehmen","Facility Management","Gewerbeimmobilienverwaltung"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Gewerbe":["Hotel","Bürogebäude","Einzelhandel","Gewerbepark"],"Bau":["Bauunternehmen","Facility Management","Generalunternehmer"]},negative_keywords:["privat","selber streichen","diy","job","ausbildung","kleinanzeigen","forum"],bad_fit_signals:["privat","diy","job","kleinanzeige","selbst streichen"],scoring_signals:["verwaltung","mieterwechsel","objekt","hotel","gewerbe","bau","renovierung","wohnanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","Hotel","Bauunternehmen","Bürogebäude","Einzelhandel"],ideal_customer_profiles:["regelmäßiger Renovierungsbedarf","Mieterwechsel","Objektbestand"],google_place_types:["property_management_company","lodging","real_estate_agency"]},
  {industry_id:"elektro_gebaeudetechnik",label:"Elektro / Gebäudetechnik",sort_order:14,own_services:["Elektroinstallation","Gebäudetechnik","Wartung","E-Check","Beleuchtung","Netzwerktechnik","Smart Building","Sicherheitstechnik","Photovoltaik","Ladestationen"],target_customer_types:["Hausverwaltungen","Gewerbeobjekte","Industriebetriebe","Hotels","Bürogebäude","Bauunternehmen","Facility Management Firmen","Einzelhandel","Wohnungsbaugesellschaften","Praxen"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen","Jobs","DIY-Anfragen"],searchable_business_categories:["Hausverwaltung","Gewerbeimmobilie","Industrieunternehmen","Hotel","Bürogebäude","Bauunternehmen","Facility Management","Einzelhandel","Wohnungsbaugesellschaft","Arztpraxis"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Wohnungsbaugesellschaft","Gewerbeimmobilie"],"Gewerbe":["Bürogebäude","Hotel","Einzelhandel","Gewerbepark"],"Industrie":["Industrieunternehmen","Bauunternehmen","Facility Management"]},negative_keywords:["privat","diy","job","karriere","ausbildung","forum"],bad_fit_signals:["privat","diy","job","forum","hobby"],scoring_signals:["technik","gebäude","wartung","gewerbe","industrie","verwaltung","objekt","anlage"],query_priority:["Hausverwaltung","Industrieunternehmen","Hotel","Bürogebäude","Bauunternehmen","Facility Management"],ideal_customer_profiles:["technischer Wartungsbedarf","mehrere Objekte","Modernisierungsbedarf"],google_place_types:["property_management_company","lodging","electrician"]},
  {industry_id:"shk",label:"SHK / Sanitär / Heizung / Klima",sort_order:15,own_services:["Sanitär","Heizung","Klima","Wartung","Badsanierung","Rohrreinigung","Notdienst","Heizungsmodernisierung","Lüftungstechnik"],target_customer_types:["Hausverwaltungen","Hotels","Pflegeheime","Gewerbeobjekte","Bürogebäude","Wohnungsbaugesellschaften","Facility Management Firmen","Industriebetriebe","Praxen","Gastronomiebetriebe"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen","DIY","Jobs"],searchable_business_categories:["Hausverwaltung","Hotel","Pflegeheim","Gewerbeimmobilie","Bürogebäude","Wohnungsbaugesellschaft","Facility Management","Industrieunternehmen","Arztpraxis","Gastronomie"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Wohnungsbaugesellschaft","Gewerbeimmobilie"],"Gewerbe":["Hotel","Bürogebäude","Gastronomie","Gewerbepark"],"Pflege":["Pflegeheim","Seniorenheim","Facility Management"]},negative_keywords:["privat","diy","job","ausbildung","forum","selber machen"],bad_fit_signals:["privat","diy","job","forum","selbst"],scoring_signals:["wartung","heizung","sanitär","gewerbe","hotel","pflege","verwaltung","objekt","anlage"],query_priority:["Hausverwaltung","Hotel","Pflegeheim","Bürogebäude","Industrieunternehmen","Gastronomie"],ideal_customer_profiles:["regelmäßiger Wartungsbedarf","viele sanitäre Anlagen","Notdienstbedarf"],google_place_types:["property_management_company","lodging","hospital","plumber"]},
  {industry_id:"eventservice",label:"Eventservice",sort_order:16,own_services:["Eventtechnik","Veranstaltungsservice","Aufbau","Abbau","Personal","Ton- und Lichttechnik","Messebau","Bühnenbau","Eventlogistik"],target_customer_types:["Eventlocations","Messeveranstalter","Hotels","Unternehmen","Marketingagenturen","Stadtverwaltungen","Kongresszentren","Seminarzentren","Veranstalter"],excluded_customer_types:["private Geburtstage","Privatfeiern","Hochzeiten privat","Kleinanzeigen","Jobs"],searchable_business_categories:["Eventlocation","Messeveranstalter","Hotel","Marketingagentur","Kongresszentrum","Seminarzentrum","Veranstalter","Messezentrum","Eventhalle","Tagungszentrum"],search_keyword_variants:{"Event":["Eventlocation","Veranstalter","Kongresszentrum","Eventhalle"],"Messe":["Messeveranstalter","Messezentrum","Messebau"],"Business":["Tagungshotel","Marketingagentur","Seminarzentrum"]},negative_keywords:["privat","geburtstag","hochzeit","kleinanzeigen","job","karriere","familienfeier"],bad_fit_signals:["privat","geburtstag","hochzeit","job","familienfeier"],scoring_signals:["event","messe","kongress","veranstaltung","hotel","agentur","b2b","tagung","bühne"],query_priority:["Eventlocation","Kongresszentrum","Messeveranstalter","Hotel","Seminarzentrum","Marketingagentur"],ideal_customer_profiles:["regelmäßige Events","professionelle Veranstaltungen","Messebetrieb"],google_place_types:["event_venue","lodging","conference_center","stadium"]},
  {industry_id:"marketing_webdesign_werbung",label:"Marketing / Webdesign / Werbung",sort_order:17,own_services:["Webdesign","SEO","Google Ads","Social Media","Branding","Grafikdesign","Online Marketing","Performance Marketing","Local SEO","Landingpages"],target_customer_types:["Handwerksbetriebe","Arztpraxen","Steuerberater","Kanzleien","Restaurants","Hotels","Immobilienmakler","lokale Dienstleister","Fitnessstudios","Einzelhandel"],excluded_customer_types:["Privatpersonen","Vereine ohne Budget","Hobbyprojekte","Jobs"],searchable_business_categories:["Handwerksbetrieb","Arztpraxis","Steuerberater","Rechtsanwalt","Restaurant","Hotel","Immobilienmakler","Fitnessstudio","Einzelhandel","Unternehmensberatung","Zahnarztpraxis","Autohaus","Bauunternehmen"],search_keyword_variants:{"Lokale Dienstleister":["Handwerksbetrieb","Arztpraxis","Restaurant","Fitnessstudio"],"Beratung":["Steuerberater","Rechtsanwalt","Unternehmensberatung"],"Handel":["Einzelhandel","Autohaus","Hotel"]},negative_keywords:["privat","hobby","gratis","job","karriere","ehrenamt"],bad_fit_signals:["privat","hobby","gratis","job","ehrenamt"],scoring_signals:["lokal","dienstleister","praxis","kanzlei","hotel","shop","restaurant","handwerk","immobilien"],query_priority:["Handwerksbetrieb","Arztpraxis","Restaurant","Steuerberater","Hotel","Fitnessstudio","Einzelhandel"],ideal_customer_profiles:["lokal sichtbarkeitsabhängig","schwache Website","Leadbedarf"],google_place_types:["doctor","lawyer","restaurant","gym","car_dealer","accounting"]},
  {industry_id:"personal_zeitarbeit",label:"Personal / Zeitarbeit",sort_order:18,own_services:["Zeitarbeit","Personalvermittlung","Recruiting","Arbeitnehmerüberlassung","Fachkräftevermittlung","Aushilfspersonal","Industriepersonal","Pflegepersonal","Logistikpersonal"],target_customer_types:["Logistikunternehmen","Industriebetriebe","Produktionsbetriebe","Pflegeheime","Hotels","Gastronomie","Bauunternehmen","Lagerbetriebe","Reinigungsunternehmen","Einzelhandel","Callcenter"],excluded_customer_types:["Jobsuchende","Bewerber","Privatpersonen","Vereine"],searchable_business_categories:["Logistikunternehmen","Industrieunternehmen","Produktionsbetrieb","Pflegeheim","Hotel","Gastronomie","Bauunternehmen","Lagerbetrieb","Reinigungsunternehmen","Einzelhandel","Callcenter"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Produktionsbetrieb","Maschinenbau"],"Logistik":["Logistikunternehmen","Lagerbetrieb","Spedition"],"Pflege":["Pflegeheim","Seniorenheim","Klinik","Pflegedienst"],"Gastronomie":["Hotel","Gastronomie","Restaurant"]},negative_keywords:["bewerbung","jobs","stellenangebot","karriere","ausbildung","praktikum","job suche"],bad_fit_signals:["bewerbung","job","karriere","praktikum","stellengesuch","jobsuche"],scoring_signals:["produktion","logistik","pflege","hotel","schicht","lager","personalbedarf","industrie"],query_priority:["Logistikunternehmen","Industrieunternehmen","Pflegeheim","Produktionsbetrieb","Hotel","Gastronomie"],ideal_customer_profiles:["hoher Personalbedarf","Schichtbetrieb","saisonaler Bedarf"],google_place_types:["storage","lodging","hospital","restaurant"]},
  {industry_id:"buchhaltung_steuernahe_dienste",label:"Buchhaltung / steuernahe Dienste",sort_order:19,own_services:["Buchhaltung","Lohnbuchhaltung","Belegsortierung","Rechnungswesen","Controlling","Büroservice","vorbereitende Buchhaltung","Finanzorganisation"],target_customer_types:["Kleinunternehmen","Handwerksbetriebe","Gastronomie","Einzelhandel","Startups","Freiberufler","Pflegedienste","Immobilienverwaltungen","Agenturen","Dienstleister"],excluded_customer_types:["Privatpersonen","Jobs","Vereine ohne Budget"],searchable_business_categories:["Handwerksbetrieb","Restaurant","Einzelhandel","Pflegedienst","Immobilienverwaltung","Agentur","Dienstleister","Gastronomie","Unternehmensberatung","Bauunternehmen"],search_keyword_variants:{"Lokale Unternehmen":["Handwerksbetrieb","Restaurant","Einzelhandel","Gastronomie"],"Dienstleister":["Agentur","Pflegedienst","Immobilienverwaltung"],"Beratung":["Unternehmensberatung","Dienstleister","Bauunternehmen"]},negative_keywords:["privat","job","karriere","ausbildung","kostenlos","forum"],bad_fit_signals:["privat","forum","job","kostenlos","selbst"],scoring_signals:["unternehmen","handel","handwerk","agentur","shop","dienstleister","pflege","büro"],query_priority:["Handwerksbetrieb","Restaurant","Einzelhandel","Pflegedienst","Agentur","Immobilienverwaltung"],ideal_customer_profiles:["laufende Belege","regelmäßige Buchführungspflicht"],google_place_types:["restaurant","car_repair","doctor"]},
  {industry_id:"industrieservice",label:"Industrieservice",sort_order:20,own_services:["Maschinenreinigung","Industriewartung","Anlagenservice","Werkshallenreinigung","Produktionsunterstützung","Technischer Service","Instandhaltung","Sonderreinigung"],target_customer_types:["Produktionsbetriebe","Maschinenbauunternehmen","Metallbauunternehmen","Logistikzentren","Chemiebetriebe","Lebensmittelproduktion","Industrieparks","Werkshallen","Automobilzulieferer","Kunststoffverarbeitung"],excluded_customer_types:["Privatpersonen","kleine Werkstätten ohne Budget","Jobs"],searchable_business_categories:["Produktionsbetrieb","Maschinenbau","Metallbau","Logistikzentrum","Chemiebetrieb","Lebensmittelhersteller","Industriepark","Automobilzulieferer","Kunststoffverarbeitung","Industrieunternehmen"],search_keyword_variants:{"Produktion":["Produktionsbetrieb","Industrieunternehmen","Lebensmittelhersteller"],"Technik":["Maschinenbau","Metallbau","Kunststoffverarbeitung","Automobilzulieferer"],"Standorte":["Industriepark","Logistikzentrum","Chemiebetrieb"]},negative_keywords:["privat","job","karriere","ausbildung","hobbywerkstatt"],bad_fit_signals:["privat","hobby","job","klein","werkstatt privat"],scoring_signals:["produktion","industrie","maschine","anlage","werk","halle","wartung","technik"],query_priority:["Produktionsbetrieb","Industrieunternehmen","Maschinenbau","Logistikzentrum","Metallbau","Lebensmittelhersteller"],ideal_customer_profiles:["laufende Produktion","technische Anlagen","Schichtbetrieb"],google_place_types:["storage","moving_company"]},
  {industry_id:"fuhrparkservice_fahrzeugpflege",label:"Fuhrparkservice / Fahrzeugpflege",sort_order:21,own_services:["Fahrzeugpflege","Fuhrparkreinigung","Innenreinigung","Außenreinigung","Aufbereitung","Hol- und Bringservice","Flottenservice","Smart Repair","Reifenservice"],target_customer_types:["Autohäuser","Taxiunternehmen","Pflegedienste","Handwerksbetriebe","Logistikunternehmen","Speditionen","Mietwagenfirmen","Fahrschulen","Flottenbetreiber","Lieferdienste","Kommunale Betriebe"],excluded_customer_types:["Privatfahrzeuge","Einmalige Kleinaufträge","Kleinanzeigen","Jobs"],searchable_business_categories:["Autohaus","Taxiunternehmen","Pflegedienst","Handwerksbetrieb","Logistikunternehmen","Spedition","Mietwagenfirma","Fahrschule","Lieferdienst","Kommunaler Betrieb","Fuhrparkbetrieb"],search_keyword_variants:{"Flotte":["Taxiunternehmen","Pflegedienst","Lieferdienst","Mietwagenfirma"],"Auto":["Autohaus","Fahrschule","Fuhrparkbetrieb"],"Gewerbe":["Handwerksbetrieb","Logistikunternehmen","Spedition"]},negative_keywords:["privat","gebrauchtwagen privat","job","kleinanzeigen","selber reinigen","auto privat verkaufen"],bad_fit_signals:["privat","kleinanzeige","job","einzelfahrzeug","gebrauchtwagen privat"],scoring_signals:["flotte","fahrzeuge","lieferung","taxi","pflege","autohaus","logistik","fuhrpark"],query_priority:["Autohaus","Taxiunternehmen","Logistikunternehmen","Handwerksbetrieb","Pflegedienst","Mietwagenfirma"],ideal_customer_profiles:["mehrere Fahrzeuge","regelmäßige Reinigung","Flotte"],google_place_types:["car_dealer","taxi_stand","car_rental"]},
  {industry_id:"pflege_betreuung",label:"Pflege / Betreuung",sort_order:22,own_services:["Pflege","Betreuung","Alltagsbegleitung","Seniorenbetreuung","Ambulante Pflege","Haushaltshilfe","Entlastungsleistungen","Demenzbetreuung"],target_customer_types:["Pflegeheime","Seniorenresidenzen","Betreutes Wohnen","Kliniken","Reha-Zentren","Sozialdienste","Betreuungsvereine","Ärztehäuser","Pflegedienste","Kommunale Sozialstellen"],excluded_customer_types:["Privatpersonen ohne Leistungsrahmen","Jobs","Foren","Selbsthilfe ohne Budget"],searchable_business_categories:["Pflegeheim","Seniorenresidenz","Betreutes Wohnen","Klinik","Reha Zentrum","Sozialdienst","Betreuungsverein","Ärztehaus","Pflegedienst","Sozialstation"],search_keyword_variants:{"Senioren":["Pflegeheim","Seniorenresidenz","Betreutes Wohnen","Altenheim"],"Medizin":["Klinik","Reha Zentrum","Ärztehaus","Pflegedienst"],"Sozial":["Sozialdienst","Betreuungsverein","Sozialstation"]},negative_keywords:["job","karriere","ausbildung","forum","privat","erfahrung","selbsthilfe"],bad_fit_signals:["job","forum","privat","erfahrung","selbsthilfe"],scoring_signals:["pflege","senioren","betreuung","sozial","reha","klinik","wohnen","station"],query_priority:["Pflegeheim","Seniorenresidenz","Klinik","Reha Zentrum","Sozialdienst","Pflegedienst"],ideal_customer_profiles:["regelmäßiger Betreuungsbedarf","Senioren-Zielgruppe","soziale Versorgung"],google_place_types:["hospital","doctor","health"]},
  {industry_id:"schulungen_weiterbildung",label:"Schulungen / Weiterbildung",sort_order:23,own_services:["Schulungen","Weiterbildung","Seminare","Mitarbeiterschulung","Arbeitssicherheit","Verkaufstraining","IT-Schulung","Führungskräftetraining","Pflichtunterweisungen"],target_customer_types:["Unternehmen","Industriebetriebe","Pflegeheime","Hotels","Logistikunternehmen","Handwerksbetriebe","Bildungsträger","Kommunen","Schulen","Einzelhandel","Callcenter"],excluded_customer_types:["Privatpersonen","Schülernachhilfe privat","Hobbykurse","Jobs"],searchable_business_categories:["Industrieunternehmen","Pflegeheim","Hotel","Logistikunternehmen","Handwerksbetrieb","Bildungsträger","Schule","Einzelhandel","Callcenter","Unternehmensberatung","Produktionsbetrieb"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Logistikunternehmen","Produktionsbetrieb"],"Sozial":["Pflegeheim","Hotel","Einzelhandel","Callcenter"],"Öffentlich":["Bildungsträger","Schule","Handwerksbetrieb"]},negative_keywords:["privat","nachhilfe","hobby","job","karriere","kostenlos"],bad_fit_signals:["privat","nachhilfe","hobby","job","kostenlos"],scoring_signals:["mitarbeiter","schulung","industrie","pflege","logistik","compliance","unternehmen","betrieb"],query_priority:["Industrieunternehmen","Pflegeheim","Hotel","Logistikunternehmen","Handwerksbetrieb","Bildungsträger"],ideal_customer_profiles:["mehrere Mitarbeitende","Schulungspflicht","Compliance"],google_place_types:["school","hospital","lodging"]}
];

const TAXONOMY_VERSION = "v4-db-2026-05";

// ── Helpers ──────────────────────────────────────────────────────────────────

function computeHash(entry) {
  // Simple deterministic hash der relevanten Felder für Sync-Validierung
  const relevant = [
    entry.industry_id,
    entry.label,
    entry.target_customer_types,
    entry.searchable_business_categories,
    entry.search_keyword_variants,
    entry.negative_keywords,
    entry.scoring_signals,
    entry.query_priority,
  ].map(v => typeof v === 'object' ? JSON.stringify(v) : String(v || '')).join('|');
  // FNV-1a 32-bit hash (keine Crypto-API nötig)
  let hash = 0x811c9dc5;
  for (let i = 0; i < relevant.length; i++) {
    hash ^= relevant.charCodeAt(i);
    hash = (hash * 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

function parseJsonField(val, fallback = []) {
  if (!val) return fallback;
  if (Array.isArray(val) || typeof val === 'object') return val;
  try { return JSON.parse(val); } catch { return fallback; }
}

function dbEntryToProfile(entry) {
  return {
    id: entry.industry_id,
    label: entry.label,
    sort_order: entry.sort_order || 99,
    ownServices: parseJsonField(entry.own_services),
    targetCustomerTypes: parseJsonField(entry.target_customer_types),
    excludedCustomerTypes: parseJsonField(entry.excluded_customer_types),
    searchableBusinessCategories: parseJsonField(entry.searchable_business_categories),
    searchKeywordVariants: parseJsonField(entry.search_keyword_variants, {}),
    negativeKeywords: parseJsonField(entry.negative_keywords),
    badFitSignals: parseJsonField(entry.bad_fit_signals),
    scoringSignals: parseJsonField(entry.scoring_signals),
    queryPriority: parseJsonField(entry.query_priority),
    idealCustomerProfiles: parseJsonField(entry.ideal_customer_profiles),
    googlePlaceTypes: parseJsonField(entry.google_place_types),
    content_hash: entry.content_hash,
    version: entry.version || TAXONOMY_VERSION,
  };
}

function seedEntryToDbRecord(seed) {
  return {
    industry_id: seed.industry_id,
    label: seed.label,
    version: TAXONOMY_VERSION,
    is_active: true,
    sort_order: seed.sort_order || 99,
    own_services: JSON.stringify(seed.own_services || []),
    target_customer_types: JSON.stringify(seed.target_customer_types || []),
    excluded_customer_types: JSON.stringify(seed.excluded_customer_types || []),
    searchable_business_categories: JSON.stringify(seed.searchable_business_categories || []),
    search_keyword_variants: JSON.stringify(seed.search_keyword_variants || {}),
    negative_keywords: JSON.stringify(seed.negative_keywords || []),
    bad_fit_signals: JSON.stringify(seed.bad_fit_signals || []),
    scoring_signals: JSON.stringify(seed.scoring_signals || []),
    query_priority: JSON.stringify(seed.query_priority || []),
    ideal_customer_profiles: JSON.stringify(seed.ideal_customer_profiles || []),
    google_place_types: JSON.stringify(seed.google_place_types || []),
    content_hash: computeHash(seed),
  };
}

// ── MAIN ─────────────────────────────────────────────────────────────────────

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Auth: öffentlicher Lesezugriff für Frontend-Onboarding + authenticated für Admin-Writes
    let user = null;
    try { user = await base44.auth.me(); } catch {}

    const body = await req.json().catch(() => ({}));
    const action = body.action || 'list'; // list | seed | get_single

    // ── list: alle aktiven Einträge zurückgeben ───────────────────────────────
    if (action === 'list') {
      let entries = await base44.asServiceRole.entities.TaxonomyEntry.filter(
        { is_active: true }, 'sort_order', 100
      );

      // Self-seeding: Falls DB leer, Seed-Daten einmalig schreiben
      if (entries.length === 0) {
        console.info('[getTaxonomy] DB leer – initialisiere mit Seed-Daten...');
        const createOps = TAXONOMY_SEED.map(seed =>
          base44.asServiceRole.entities.TaxonomyEntry.create(seedEntryToDbRecord(seed))
        );
        await Promise.all(createOps);
        entries = await base44.asServiceRole.entities.TaxonomyEntry.filter(
          { is_active: true }, 'sort_order', 100
        );
        console.info(`[getTaxonomy] Seed abgeschlossen: ${entries.length} Einträge`);
      }

      const profiles = entries.map(dbEntryToProfile).sort((a, b) => a.sort_order - b.sort_order);

      // Taxonomy-Hash = Hash aller Entry-Hashes (Reihenfolge nach industry_id sort)
      const allHashes = profiles.map(p => p.content_hash || '').join('');
      let taxonomyHash = 0x811c9dc5;
      for (let i = 0; i < allHashes.length; i++) {
        taxonomyHash ^= allHashes.charCodeAt(i);
        taxonomyHash = (taxonomyHash * 0x01000193) >>> 0;
      }
      const taxonomy_hash = taxonomyHash.toString(16).padStart(8, '0');

      return Response.json({
        success: true,
        version: TAXONOMY_VERSION,
        taxonomy_hash,
        count: profiles.length,
        profiles,
      });
    }

    // ── seed_reset: Seed-Daten zurückschreiben (Admin only) ──────────────────
    if (action === 'seed_reset') {
      if (!user || !['admin', 'platform_owner', 'platform_admin'].includes(user.role)) {
        return Response.json({ error: 'Admin-Zugriff erforderlich', success: false }, { status: 403 });
      }
      // Bestehende deaktivieren
      const existing = await base44.asServiceRole.entities.TaxonomyEntry.filter({}, 'sort_order', 200);
      await Promise.all(existing.map(e => base44.asServiceRole.entities.TaxonomyEntry.update(e.id, { is_active: false })));
      // Seed neu schreiben
      const createOps = TAXONOMY_SEED.map(seed =>
        base44.asServiceRole.entities.TaxonomyEntry.create(seedEntryToDbRecord(seed))
      );
      await Promise.all(createOps);
      return Response.json({ success: true, message: `${TAXONOMY_SEED.length} Einträge neu gesetzt`, version: TAXONOMY_VERSION });
    }

    // ── get_single: Einzelnen Eintrag per industry_id ────────────────────────
    if (action === 'get_single') {
      const { industry_id } = body;
      if (!industry_id) return Response.json({ error: 'industry_id fehlt', success: false }, { status: 400 });
      const entries = await base44.asServiceRole.entities.TaxonomyEntry.filter({ industry_id, is_active: true });
      if (!entries[0]) return Response.json({ error: 'Nicht gefunden', success: false }, { status: 404 });
      return Response.json({ success: true, profile: dbEntryToProfile(entries[0]) });
    }

    return Response.json({ error: 'Unbekannte Action', success: false }, { status: 400 });

  } catch (error) {
    console.error('[getTaxonomy] Error:', error?.message);
    return Response.json({ error: error?.message || 'Interner Fehler', success: false }, { status: 500 });
  }
});