/**
 * getTaxonomy
 * ===========
 * Kanonische Taxonomie-Quelle für Frontend und Backend.
 *
 * ARCHITEKTUR:
 * - TaxonomyEntry Entitäten in der Datenbank sind die EINZIGE Wahrheitsquelle.
 * - Frontend ruft diese Function auf → kein statisches Inline-Preset mehr nötig.
 * - startResearchRun ruft diese Function auf → bettet Taxonomie in search_plan_json ein.
 * - processResearchRun liest Taxonomie aus search_plan_json → kein DB-Call im Batch-Loop.
 *
 * HASH-SYSTEM:
 * - Jeder Eintrag hat einen content_hash (SHA-256 der relevanten Felder).
 * - taxonomy_hash im ResearchRun = Hash aller aktiven Einträge → vollständige Rückverfolgung.
 *
 * FALLBACK:
 * - Wenn DB leer → eingebetteter SEED wird verwendet + in DB geschrieben.
 * - Dadurch ist die Function beim ersten Aufruf selbst-initialisierend.
 */

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// ── SEED-Daten: Kanonische Taxonomie (wird beim ersten Aufruf in DB geschrieben) ──
// Dies ist die EINZIGE inhaltliche Quelle. Frontend + Backend lesen aus der DB.
// Änderungen hier → nächster Aufruf schreibt sie in die DB (wenn Einträge fehlen).
const TAXONOMY_SEED = [
  {industry_id:"gebaeudereinigung",label:"Gebäudereinigung",sort_order:1,status:"production_ready",profile_group:"Gebäude & Facility",aliases:["Reinigung","Büroreinigung","Reinigungsfirma","Gebäudeservice","Objektreinigung"],own_services:["Büroreinigung","Treppenhausreinigung","Praxisreinigung","Fensterreinigung","Grundreinigung","Baureinigung","Sonderreinigung","Hausmeisterdienst","Winterdienst","Teppichreinigung","Glasreinigung"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Bürogebäude","Arztpraxen","Zahnarztpraxen","Ärztehäuser","Kitas","Schulen","Pflegeheime","Seniorenheime","Hotels","Autohäuser","Fitnessstudios","Gewerbehallen","Industriebetriebe","Einzelhandel","Supermärkte"],excluded_customer_types:["Privathaushalte","Einmalige Kleinstaufträge","private Wohnungen","Kleinanzeigen","Jobangebote"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Bürogebäude","Ärztehaus","Arztpraxis","Zahnarztpraxis","Kindertagesstätte","Schule","Pflegeheim","Seniorenheim","Hotel","Autohaus","Fitnessstudio","Gewerbepark","Industrieunternehmen","Einzelhandel","Supermarkt"],search_keyword_variants:{"Hausverwaltung":["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Mietverwaltung"],"Arztpraxis":["Arztpraxis","Ärztehaus","Zahnarztpraxis","Medizinisches Versorgungszentrum"],"Pflegeheim":["Pflegeheim","Seniorenheim","Seniorenresidenz","Altenheim"],"Hotel":["Hotel","Gasthof","Pension"],"Gewerbe":["Gewerbepark","Bürogebäude","Industrieunternehmen","Gewerbehalle"],"Schule":["Schule","Gymnasium","Grundschule","Berufsschule"],"Kita":["Kindertagesstätte","Kita","Kindergarten","Krippe"]},negative_keywords:["privat","job","karriere","ausbildung","stellenangebot","minijob","kleinanzeigen","wohnung gesucht","mietgesuch"],bad_fit_signals:["privat","job","karriere","kleinanzeige","einzelperson","mietgesuch","gesucht","ausbildung"],scoring_signals:["verwaltung","gewerbe","praxis","hotel","pflege","industrie","facility","büro","objekt","standort","wohnanlage","immobilien"],query_priority:["Hausverwaltung","Immobilienverwaltung","Pflegeheim","Arztpraxis","Hotel","Bürogebäude","Schule","Kita"],ideal_customer_profiles:["regelmäßiger Reinigungsbedarf","mehrere Standorte","größere Nutzfläche","laufende Objektbetreuung"],google_place_types:["property_management_company","doctor","dentist","hospital","lodging","car_dealer","gym","school"]},
  {industry_id:"sicherheitsdienst",label:"Sicherheitsdienst",sort_order:2,status:"production_ready",profile_group:"Sicherheit",aliases:["Security","Wachdienst","Bewachung","Objektschutz","Securitydienst"],own_services:["Objektschutz","Baustellenbewachung","Veranstaltungsschutz","Doorman-Service","Revierdienst","Alarmverfolgung","Werkschutz","Empfangsdienst","Parkplatzüberwachung"],target_customer_types:["Baustellen","Bauunternehmen","Logistikzentren","Industriebetriebe","Veranstalter","Hotels","Einkaufszentren","Parkhäuser","Messeveranstalter","Eventlocations","Gewerbeparks","Einzelhandel","Wohnanlagen"],excluded_customer_types:["Privatpersonen","kleine Privatfeiern","Vereine ohne Budget","Jobsuchende"],searchable_business_categories:["Bauunternehmen","Logistikzentrum","Industrieunternehmen","Veranstalter","Eventlocation","Hotel","Einkaufszentrum","Parkhaus","Messeveranstalter","Gewerbepark","Einzelhandel","Facility Management"],search_keyword_variants:{"Baustelle":["Bauunternehmen","Bauträger","Baustelle","Generalunternehmer"],"Event":["Eventlocation","Veranstalter","Messeveranstalter","Kongresszentrum"],"Industrie":["Industriebetrieb","Gewerbepark","Logistikzentrum","Produktionsbetrieb"],"Hotel":["Hotel","Tagungshotel","Kongresshotel"],"Einzelhandel":["Einkaufszentrum","Shopping Center","Einzelhandel"]},negative_keywords:["job","stellenangebot","ausbildung","security job","privat","ehrenamt","karriere","bewerber"],bad_fit_signals:["job","karriere","privat","ehrenamt","verein klein","ausbildung","bewerber"],scoring_signals:["objektschutz","baustelle","logistik","industrie","veranstaltung","zugang","werkschutz","publikumsverkehr","gewerbe","lager","messe"],query_priority:["Bauunternehmen","Logistikzentrum","Industrieunternehmen","Hotel","Eventlocation","Einkaufszentrum"],ideal_customer_profiles:["hoher Sicherheitsbedarf","Publikumsverkehr","wertvolle Güter","Nachtbetrieb"],google_place_types:["shopping_mall","lodging","event_venue","stadium","parking","storage"]},
  {industry_id:"it_service",label:"IT-Service",sort_order:3,status:"production_ready",profile_group:"IT & Beratung",aliases:["IT","Informatik","EDV","Managed IT","IT-Dienstleister","Computertechnik","IT-Support","Netzwerk"],own_services:["IT-Support","Managed Services","Serverbetreuung","Netzwerkbetreuung","Microsoft 365","Cybersecurity","Cloud-Lösungen","Backup","Telefonanlage","Hardware-Service"],target_customer_types:["Arztpraxen","Zahnarztpraxen","Steuerberater","Kanzleien","KMU","Schulen","Pflegeeinrichtungen","Handwerksbetriebe","Büros","Einzelhandel","Immobilienverwaltungen","Logistikunternehmen"],excluded_customer_types:["Privatpersonen","Gaming-PC-Anfragen","Einmalige Kleinreparaturen","Jobsuchende"],searchable_business_categories:["Arztpraxis","Zahnarztpraxis","Steuerberater","Rechtsanwalt","Kanzlei","Pflegeheim","Schule","Handwerksbetrieb","Büro","Einzelhandel","Immobilienverwaltung","Logistikunternehmen","Unternehmensberatung","Ingenieurbüro"],search_keyword_variants:{"Praxen":["Arztpraxis","Zahnarztpraxis","Ärztehaus","Medizinisches Versorgungszentrum"],"Kanzleien":["Rechtsanwalt","Kanzlei","Anwaltskanzlei","Steuerberater","Steuerberatung"],"KMU":["Handwerksbetrieb","Unternehmensberatung","Ingenieurbüro","Bürogebäude"],"Bildung":["Schule","Gymnasium","Bildungszentrum"],"Pflege":["Pflegeheim","Seniorenheim","Reha Zentrum"]},negative_keywords:["privat","gaming","job","karriere","ausbildung","computerhilfe privat","forum","blog"],bad_fit_signals:["privat","gaming","job","forum","einzelperson","haushaltsgerät","reparatur privat"],scoring_signals:["praxis","kanzlei","steuer","pflege","schule","verwaltung","daten","büro","handwerk","logistik"],query_priority:["Arztpraxis","Zahnarztpraxis","Steuerberater","Rechtsanwalt","Handwerksbetrieb","Pflegeheim","Schule"],ideal_customer_profiles:["mehrere Arbeitsplätze","regelmäßiger IT-Bedarf","sensible Daten","Compliance-Anforderungen"],google_place_types:["doctor","dentist","lawyer","accounting","school","hospital"]},
  {industry_id:"gartenbau",label:"Gartenbau",sort_order:4,status:"production_ready",profile_group:"Gebäude & Facility",aliases:["Garten","Grünpflege","Landschaftsbau","Außenanlagen","Grünanlage","Gartenservice"],own_services:["Gartenpflege","Grünanlagenpflege","Rasenpflege","Heckenschnitt","Baumpflege","Winterdienst","Außenanlagenpflege","Pflasterarbeiten","Objektpflege"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Wohnanlagen","Hotels","Gewerbeparks","Kommunen","Pflegeheime","Kitas","Schulen","Facility Management Firmen","Bürogebäude","Industriebetriebe"],excluded_customer_types:["Privatgärten","Einmalige Kleinstaufträge","Kleinanzeigen","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Wohnanlage","Hotel","Gewerbepark","Pflegeheim","Kindertagesstätte","Schule","Facility Management","Bürogebäude","Industrieunternehmen","Friedhof"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnanlage","WEG Verwaltung"],"Gewerbe":["Gewerbepark","Bürogebäude","Industriebetrieb"],"Sozial":["Pflegeheim","Kita","Schule","Altenheim"],"Hotel":["Hotel","Tagungshotel","Gasthof"]},negative_keywords:["privatgarten","privat","job","karriere","kleinanzeigen","gratis","selber machen"],bad_fit_signals:["privat","kleinanzeige","job","einzelgarten","hobby","selbst"],scoring_signals:["anlage","grünfläche","verwaltung","wohnanlage","gewerbe","hotel","pflege","objekt","außenanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","Hotel","Pflegeheim","Gewerbepark","Schule","Kita"],ideal_customer_profiles:["regelmäßige Außenpflege","größere Grünflächen","Wohnanlagenbestand"],google_place_types:["property_management_company","lodging","school","hospital"]},
  {industry_id:"catering",label:"Catering",sort_order:5,status:"production_ready",profile_group:"Gastronomie & Event",aliases:["Verpflegung","Essen","Kantinenbetrieb","Cateringservice","Food Service","Kantine"],own_services:["Business Catering","Event Catering","Messe Catering","Kita Catering","Schulverpflegung","Kantinenservice","Fingerfood","Buffet","Tagungsverpflegung"],target_customer_types:["Eventlocations","Tagungshotels","Seminarzentren","Messeveranstalter","Kongresszentren","Unternehmen","Bürokomplexe","Kitas","Schulen","Pflegeheime","Hotels","Coworking Spaces"],excluded_customer_types:["Privatfeiern","Hochzeiten privat","Geburtstage privat","Kleinanzeigen"],searchable_business_categories:["Eventlocation","Tagungshotel","Seminarzentrum","Messeveranstalter","Kongresszentrum","Bürogebäude","Kindertagesstätte","Schule","Pflegeheim","Hotel","Coworking Space","Veranstalter","Unternehmensberatung"],search_keyword_variants:{"Event":["Eventlocation","Veranstalter","Messeveranstalter","Kongresszentrum","Eventhalle"],"Business":["Bürogebäude","Unternehmensberatung","Coworking Space","Business Center"],"Bildung":["Kindertagesstätte","Schule","Seminarzentrum","Bildungszentrum"],"Hotel":["Tagungshotel","Kongresshotel","Hotel"]},negative_keywords:["privat","hochzeit","geburtstag","familienfeier","job","karriere","kleinanzeigen","selbst kochen"],bad_fit_signals:["privat","hochzeit","geburtstag","kleinanzeige","familienfeier","selbst"],scoring_signals:["event","tagung","messe","seminar","unternehmen","büro","kita","schule","hotel","kongress","veranstaltung"],query_priority:["Eventlocation","Tagungshotel","Kongresszentrum","Seminarzentrum","Bürogebäude","Kita","Schule"],ideal_customer_profiles:["regelmäßige Veranstaltungen","viele Mitarbeitende","Tagungsbetrieb"],google_place_types:["event_venue","lodging","school","conference_center"]},
  {industry_id:"handwerk",label:"Handwerk",sort_order:6,status:"production_ready",profile_group:"Handwerk & Bau",aliases:["Handwerker","Reparatur","Montage","Instandhaltung","Hausmeister","Wartung"],own_services:["Reparaturen","Instandhaltung","Renovierung","Montage","Wartung","Notdienst","Objektbetreuung","Kleinreparaturen"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Bauunternehmen","Gewerbeimmobilienverwaltungen","Facility Management Firmen","Hotels","Praxen","Bürogebäude","Einzelhandel","Wohnungsbaugesellschaften"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen ohne Budget","DIY-Anfragen","Jobangebote"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Bauunternehmen","Facility Management","Hotel","Arztpraxis","Bürogebäude","Einzelhandel","Wohnungsbaugesellschaft","Gewerbeimmobilienverwaltung"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft","WEG Verwaltung"],"Gewerbe":["Bürogebäude","Einzelhandel","Hotel","Gewerbepark"],"Bau":["Bauunternehmen","Facility Management","Generalunternehmer"]},negative_keywords:["privat","selber machen","diy","job","ausbildung","karriere","kleinanzeigen","forum"],bad_fit_signals:["privat","diy","job","kleinanzeige","selbst"],scoring_signals:["verwaltung","objekt","instandhaltung","gewerbe","hotel","bau","facility","wohnanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","Bauunternehmen","Hotel","Bürogebäude","Einzelhandel"],ideal_customer_profiles:["regelmäßiger Instandhaltungsbedarf","mehrere Objekte","Objektbestand"],google_place_types:["property_management_company","lodging","real_estate_agency"]},
  {industry_id:"spedition_logistik",label:"Spedition / Logistik",sort_order:7,status:"production_ready",profile_group:"Transport & Logistik",aliases:["Spedition","Logistik","Transport","Frachtführer","LKW","Kurier","Lieferdienst","Spediteur"],own_services:["Transport","Kurierdienst","Expresslieferung","Stückgut","Palettentransport","Möbeltransport","Lagerlogistik","Auslieferung","Same-Day Delivery"],target_customer_types:["Online-Shops","Großhändler","Produktionsbetriebe","Industriebetriebe","Möbelhäuser","Baustoffhändler","Maschinenbauunternehmen","Lebensmittelgroßhandel","Eventfirmen","Einzelhandel","E-Commerce-Unternehmen"],excluded_customer_types:["Privatumzüge","Einzelne Privattransporte","Kleinanzeigen","Jobs"],searchable_business_categories:["Großhandel","Produktionsbetrieb","Industrieunternehmen","Möbelhaus","Baustoffhandel","Maschinenbau","Lebensmittelgroßhandel","Eventagentur","Einzelhandel","Versandhandel","Handelsunternehmen","Küchenstudio"],search_keyword_variants:{"E-Commerce":["Versandhandel","Online Händler","Handelsunternehmen"],"Industrie":["Produktionsbetrieb","Industrieunternehmen","Maschinenbau"],"Handel":["Großhandel","Möbelhaus","Baustoffhandel","Lebensmittelgroßhandel"],"Event":["Eventagentur","Messeveranstalter","Veranstaltungstechnik"]},negative_keywords:["privat","umzug privat","job","fahrer gesucht","karriere","kleinanzeigen","führerschein"],bad_fit_signals:["privat","job","kleinanzeige","einzeltransport","möbel privat"],scoring_signals:["versand","logistik","lager","großhandel","produktion","lieferung","handel","import","export"],query_priority:["Großhandel","Produktionsbetrieb","Industrieunternehmen","Möbelhaus","Maschinenbau","Baustoffhandel"],ideal_customer_profiles:["regelmäßiger Versand","wiederkehrende Transporte","hohes Sendungsvolumen"],google_place_types:["storage","moving_company","wholesale_store"]},
  {industry_id:"gesundheit_medizin",label:"Gesundheit / Medizin",sort_order:8,status:"production_ready",profile_group:"Gesundheit & Pflege",aliases:["Medizin","Gesundheit","Praxisservice","Arzt","Klinik","Ambulanz"],own_services:["medizinische Dienstleistung","Therapie","Pflegebezogene Dienstleistung","Praxisservice","Gesundheitsberatung","Betriebliches Gesundheitsmanagement"],target_customer_types:["Arztpraxen","Zahnarztpraxen","Therapiezentren","Pflegeheime","Seniorenheime","Apotheken","Reha-Zentren","Privatkliniken","Gesundheitszentren","Physiotherapien","Ergotherapien"],excluded_customer_types:["Privatpersonen","Foren","Selbsthilfegruppen ohne Budget","Jobanzeigen"],searchable_business_categories:["Arztpraxis","Zahnarztpraxis","Therapiezentrum","Pflegeheim","Seniorenheim","Apotheke","Reha Zentrum","Privatklinik","Gesundheitszentrum","Physiotherapie","Ergotherapie","Ärztehaus"],search_keyword_variants:{"Praxis":["Arztpraxis","Zahnarztpraxis","Ärztehaus","Medizinisches Versorgungszentrum"],"Therapie":["Physiotherapie","Ergotherapie","Therapiezentrum","Logopädie"],"Pflege":["Pflegeheim","Seniorenheim","Reha Zentrum","Klinik"]},negative_keywords:["privat","forum","job","karriere","ausbildung","krankheit erfahrung","selbsthilfe","blog"],bad_fit_signals:["forum","privat","job","erfahrung","selbsthilfe","blog"],scoring_signals:["praxis","gesundheit","pflege","therapie","reha","klinik","zentrum","apotheke","medizin"],query_priority:["Arztpraxis","Zahnarztpraxis","Pflegeheim","Physiotherapie","Therapiezentrum","Ärztehaus"],ideal_customer_profiles:["professioneller Gesundheitsbetrieb","regelmäßiger Bedarf","Patientenverkehr"],google_place_types:["doctor","dentist","hospital","pharmacy","physiotherapist","health"]},
  {industry_id:"immobilien",label:"Immobilien",sort_order:9,status:"production_ready",profile_group:"Gebäude & Facility",aliases:["Immobilienverwaltung","Hausverwaltung","WEG","Wohnungswirtschaft","Property Management"],own_services:["Vermietung","Verwaltung","Verkauf","Gewerbeimmobilien","Projektentwicklung","Immobilienberatung","Standortvermittlung"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","WEG-Verwaltungen","Bauträger","Projektentwickler","Wohnungsbaugesellschaften","Gewerbeimmobilienverwaltungen","Immobiliengesellschaften","Property Management Firmen"],excluded_customer_types:["Privathaushalte","private Vermieter","Ferienwohnung privat","Wohnung gesucht","Mietgesuch"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Bauträger","Projektentwickler","Wohnungsbaugesellschaft","Immobiliengesellschaft","Gewerbeimmobilienverwaltung","Property Management","Facility Management Immobilien","Mietverwaltung"],search_keyword_variants:{"Hausverwaltung":["Hausverwaltung","WEG Verwaltung","Immobilienverwaltung","Mietverwaltung","Objektverwaltung"],"Bauträger":["Bauträger","Wohnbaugesellschaft","Projektentwickler Immobilien","Immobilienprojektentwicklung"],"Gewerbe":["Gewerbeimmobilienverwaltung","Property Management","Facility Management Immobilien"]},negative_keywords:["privat","wohnung gesucht","mietgesuch","ferienwohnung","airbnb","job","karriere","vermiete privat","suche wohnung"],bad_fit_signals:["privat","mietgesuch","wohnung gesucht","ferienwohnung","job","airbnb"],scoring_signals:["verwaltung","weg","gewerbeimmobilien","bestand","objektverwaltung","property management","projektentwicklung","bauträger","wohnanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Bauträger","Wohnungsbaugesellschaft","Property Management"],ideal_customer_profiles:["Eigentümer","Investoren","Bestandshalter","Objektbestand"],google_place_types:["property_management_company","real_estate_agency"]},
  {industry_id:"lager_fulfillment",label:"Lager / Fulfillment",sort_order:10,status:"production_ready",profile_group:"Transport & Logistik",aliases:["Lagerlogistik","Fulfillment","Kommissionierung","Lager","Versandabwicklung","Pick Pack"],own_services:["Fulfillment","Lagerung","Kommissionierung","Versandabwicklung","Retourenmanagement","E-Commerce Logistik","Pick & Pack","B2B-Lagerlogistik"],target_customer_types:["Online-Shops","Shopify-Händler","Amazon-Händler","Großhändler","E-Commerce-Unternehmen","Kosmetikmarken","Lebensmittelmarken","Textilhändler","Ersatzteilhändler","Importeure","Startups mit Versand"],excluded_customer_types:["Privatverkäufer","Kleinanzeigen","Dropshipping ohne Bestand","Jobs"],searchable_business_categories:["Versandhandel","Großhandel","Kosmetikmarke","Lebensmittelhersteller","Textilhandel","Ersatzteilhandel","Importeur","Handelsunternehmen","Modehändler","Online Händler"],search_keyword_variants:{"E-Commerce":["Versandhandel","Online Händler","Handelsunternehmen"],"Handel":["Großhandel","Importeur","Textilhandel","Modehändler"],"Produkte":["Kosmetikmarke","Lebensmittelhersteller","Ersatzteilhandel"]},negative_keywords:["privat","kleinanzeigen","job","karriere","ausbildung","ebay privat","zu verschenken"],bad_fit_signals:["privat","kleinanzeige","job","kein bestand","zu verschenken"],scoring_signals:["shop","versand","handel","import","retouren","lager","ecommerce","online"],query_priority:["Großhandel","Versandhandel","Importeur","Handelsunternehmen","Textilhandel"],ideal_customer_profiles:["regelmäßiger Versand","wachsender Onlinehandel","Retourenbedarf"],google_place_types:["storage","wholesale_store"]},
  {industry_id:"facility_service",label:"Facility Service",sort_order:11,status:"production_ready",profile_group:"Gebäude & Facility",aliases:["Facility","Hausmeisterservice","Objektbetreuung","Gebäudemanagement","FM"],own_services:["Hausmeisterdienst","Objektbetreuung","Gebäudemanagement","Technische Betreuung","Reinigung","Winterdienst","Grünpflege","Kleinreparaturen","Kontrolldienste"],target_customer_types:["Hausverwaltungen","Gewerbeimmobilien","Bürogebäude","Hotels","Pflegeheime","Industriebetriebe","Schulen","Kitas","Kommunen","Wohnanlagen"],excluded_customer_types:["Privathaushalte","Einmalige Kleinstaufträge","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Gewerbeimmobilie","Bürogebäude","Hotel","Pflegeheim","Industrieunternehmen","Schule","Kindertagesstätte","Wohnanlage","Gewerbepark"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnanlage","WEG Verwaltung"],"Gewerbe":["Bürogebäude","Gewerbeimmobilie","Industrieunternehmen","Gewerbepark"],"Sozial":["Pflegeheim","Schule","Kita","Altenheim"]},negative_keywords:["privat","job","karriere","ausbildung","kleinanzeigen"],bad_fit_signals:["privat","job","kleinanzeige","einzelperson"],scoring_signals:["objekt","verwaltung","gewerbe","facility","wohnanlage","technisch","gebäude","standort"],query_priority:["Hausverwaltung","Immobilienverwaltung","Bürogebäude","Hotel","Pflegeheim","Gewerbepark"],ideal_customer_profiles:["mehrere Objekte","laufender Objektbedarf","technische Betreuung"],google_place_types:["property_management_company","lodging","school"]},
  {industry_id:"entruempelung",label:"Entrümpelung",sort_order:12,status:"production_ready",profile_group:"Gebäude & Facility",aliases:["Entrümpeln","Haushaltsauflösung","Räumung","Wohnungsauflösung","Entsorgung"],own_services:["Entrümpelung","Haushaltsauflösung","Wohnungsauflösung","Nachlassauflösung","Kellerentrümpelung","Gewerbeauflösung","Messie-Wohnung","Entsorgung","Räumung"],target_customer_types:["Hausverwaltungen","Nachlassverwalter","Betreuungsbüros","Immobilienmakler","Wohnungsbaugesellschaften","Pflegeheime","Seniorenheime","Rechtsanwälte Erbrecht","Sozialdienste","Gerichtliche Betreuer"],excluded_customer_types:["Privathaushalte mit Kleinstauftrag","Sperrmüll Einzelstück","Kleinanzeigen","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Nachlassverwaltung","Betreuungsbüro","Immobilienmakler","Wohnungsbaugesellschaft","Pflegeheim","Seniorenheim","Rechtsanwalt Erbrecht","Sozialdienst"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Nachlass":["Nachlassverwaltung","Rechtsanwalt Erbrecht","Betreuungsbüro","Nachlassverwalter"],"Sozial":["Sozialdienst","Pflegeheim","Seniorenheim","Sozialstation"]},negative_keywords:["privat","sperrmüll kostenlos","kleinanzeigen","job","karriere","zu verschenken"],bad_fit_signals:["privat","kleinanzeige","zu verschenken","job","sperrmüll kostenlos"],scoring_signals:["verwaltung","nachlass","betreuung","erbrecht","wohnung","pflege","sozialdienst","objekt"],query_priority:["Hausverwaltung","Immobilienverwaltung","Sozialdienst","Pflegeheim","Betreuungsbüro","Rechtsanwalt Erbrecht"],ideal_customer_profiles:["regelmäßige Wohnungswechsel","Nachlassfälle","Erbfälle"],google_place_types:["property_management_company","lawyer"]},
  {industry_id:"maler_renovierung",label:"Maler / Renovierung",sort_order:13,status:"production_ready",profile_group:"Handwerk & Bau",aliases:["Maler","Streichen","Renovierung","Malerarbeiten","Lackieren","Tapezieren","Fassade"],own_services:["Malerarbeiten","Renovierung","Tapezieren","Lackieren","Fassadenanstrich","Innenausbau","Wohnungsrenovierung","Gewerberenovierung","Trockenbau"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Hotels","Bürogebäude","Praxen","Einzelhandel","Wohnungsbaugesellschaften","Bauunternehmen","Facility Management Firmen"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen","DIY-Anfragen","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Hotel","Bürogebäude","Arztpraxis","Einzelhandel","Wohnungsbaugesellschaft","Bauunternehmen","Facility Management","Gewerbeimmobilienverwaltung"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Gewerbe":["Hotel","Bürogebäude","Einzelhandel","Gewerbepark"],"Bau":["Bauunternehmen","Facility Management","Generalunternehmer"]},negative_keywords:["privat","selber streichen","diy","job","ausbildung","kleinanzeigen","forum"],bad_fit_signals:["privat","diy","job","kleinanzeige","selbst streichen"],scoring_signals:["verwaltung","mieterwechsel","objekt","hotel","gewerbe","bau","renovierung","wohnanlage"],query_priority:["Hausverwaltung","Immobilienverwaltung","Hotel","Bauunternehmen","Bürogebäude","Einzelhandel"],ideal_customer_profiles:["regelmäßiger Renovierungsbedarf","Mieterwechsel","Objektbestand"],google_place_types:["property_management_company","lodging","real_estate_agency"]},
  {industry_id:"elektro_gebaeudetechnik",label:"Elektro / Gebäudetechnik",sort_order:14,status:"production_ready",profile_group:"Handwerk & Bau",aliases:["Elektriker","Elektro","Elektroinstallation","Elektrotechnik","Gebäudetechnik","EPLAN"],own_services:["Elektroinstallation","Gebäudetechnik","Wartung","E-Check","Beleuchtung","Netzwerktechnik","Smart Building","Sicherheitstechnik","Photovoltaik","Ladestationen"],target_customer_types:["Hausverwaltungen","Gewerbeobjekte","Industriebetriebe","Hotels","Bürogebäude","Bauunternehmen","Facility Management Firmen","Einzelhandel","Wohnungsbaugesellschaften","Praxen"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen","Jobs","DIY-Anfragen"],searchable_business_categories:["Hausverwaltung","Gewerbeimmobilie","Industrieunternehmen","Hotel","Bürogebäude","Bauunternehmen","Facility Management","Einzelhandel","Wohnungsbaugesellschaft","Arztpraxis"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Wohnungsbaugesellschaft","Gewerbeimmobilie"],"Gewerbe":["Bürogebäude","Hotel","Einzelhandel","Gewerbepark"],"Industrie":["Industrieunternehmen","Bauunternehmen","Facility Management"]},negative_keywords:["privat","diy","job","karriere","ausbildung","forum"],bad_fit_signals:["privat","diy","job","forum","hobby"],scoring_signals:["technik","gebäude","wartung","gewerbe","industrie","verwaltung","objekt","anlage"],query_priority:["Hausverwaltung","Industrieunternehmen","Hotel","Bürogebäude","Bauunternehmen","Facility Management"],ideal_customer_profiles:["technischer Wartungsbedarf","mehrere Objekte","Modernisierungsbedarf"],google_place_types:["property_management_company","lodging","electrician"]},
  {industry_id:"shk",label:"SHK / Sanitär / Heizung / Klima",sort_order:15,status:"production_ready",profile_group:"Handwerk & Bau",aliases:["SHK","Sanitär","Heizung","Klima","Rohrreinigung","Installateur","Heizungsbauer","Klempner"],own_services:["Sanitär","Heizung","Klima","Wartung","Badsanierung","Rohrreinigung","Notdienst","Heizungsmodernisierung","Lüftungstechnik"],target_customer_types:["Hausverwaltungen","Hotels","Pflegeheime","Gewerbeobjekte","Bürogebäude","Wohnungsbaugesellschaften","Facility Management Firmen","Industriebetriebe","Praxen","Gastronomiebetriebe"],excluded_customer_types:["Privathaushalte","Kleinstreparaturen","DIY","Jobs"],searchable_business_categories:["Hausverwaltung","Hotel","Pflegeheim","Gewerbeimmobilie","Bürogebäude","Wohnungsbaugesellschaft","Facility Management","Industrieunternehmen","Arztpraxis","Gastronomie"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Wohnungsbaugesellschaft","Gewerbeimmobilie"],"Gewerbe":["Hotel","Bürogebäude","Gastronomie","Gewerbepark"],"Pflege":["Pflegeheim","Seniorenheim","Facility Management"]},negative_keywords:["privat","diy","job","ausbildung","forum","selber machen"],bad_fit_signals:["privat","diy","job","forum","selbst"],scoring_signals:["wartung","heizung","sanitär","gewerbe","hotel","pflege","verwaltung","objekt","anlage"],query_priority:["Hausverwaltung","Hotel","Pflegeheim","Bürogebäude","Industrieunternehmen","Gastronomie"],ideal_customer_profiles:["regelmäßiger Wartungsbedarf","viele sanitäre Anlagen","Notdienstbedarf"],google_place_types:["property_management_company","lodging","hospital","plumber"]},
  {industry_id:"eventservice",label:"Eventservice",sort_order:16,status:"production_ready",profile_group:"Gastronomie & Event",aliases:["Event","Veranstaltungstechnik","Eventtechnik","Ton Licht","Messebau","Bühne","Aufbau","Abbau"],own_services:["Eventtechnik","Veranstaltungsservice","Aufbau","Abbau","Personal","Ton- und Lichttechnik","Messebau","Bühnenbau","Eventlogistik"],target_customer_types:["Eventlocations","Messeveranstalter","Hotels","Unternehmen","Marketingagenturen","Stadtverwaltungen","Kongresszentren","Seminarzentren","Veranstalter"],excluded_customer_types:["private Geburtstage","Privatfeiern","Hochzeiten privat","Kleinanzeigen","Jobs"],searchable_business_categories:["Eventlocation","Messeveranstalter","Hotel","Marketingagentur","Kongresszentrum","Seminarzentrum","Veranstalter","Messezentrum","Eventhalle","Tagungszentrum"],search_keyword_variants:{"Event":["Eventlocation","Veranstalter","Kongresszentrum","Eventhalle"],"Messe":["Messeveranstalter","Messezentrum","Messebau"],"Business":["Tagungshotel","Marketingagentur","Seminarzentrum"]},negative_keywords:["privat","geburtstag","hochzeit","kleinanzeigen","job","karriere","familienfeier"],bad_fit_signals:["privat","geburtstag","hochzeit","job","familienfeier"],scoring_signals:["event","messe","kongress","veranstaltung","hotel","agentur","b2b","tagung","bühne"],query_priority:["Eventlocation","Kongresszentrum","Messeveranstalter","Hotel","Seminarzentrum","Marketingagentur"],ideal_customer_profiles:["regelmäßige Events","professionelle Veranstaltungen","Messebetrieb"],google_place_types:["event_venue","lodging","conference_center","stadium"]},
  {industry_id:"marketing_webdesign_werbung",label:"Marketing / Webdesign / Werbung",sort_order:17,status:"production_ready",profile_group:"IT & Beratung",aliases:["Marketing","Webdesign","SEO","Werbung","Agentur","Online Marketing","Website","Google Ads"],own_services:["Webdesign","SEO","Google Ads","Social Media","Branding","Grafikdesign","Online Marketing","Performance Marketing","Local SEO","Landingpages"],target_customer_types:["Handwerksbetriebe","Arztpraxen","Steuerberater","Kanzleien","Restaurants","Hotels","Immobilienmakler","lokale Dienstleister","Fitnessstudios","Einzelhandel"],excluded_customer_types:["Privatpersonen","Vereine ohne Budget","Hobbyprojekte","Jobs"],searchable_business_categories:["Handwerksbetrieb","Arztpraxis","Steuerberater","Rechtsanwalt","Restaurant","Hotel","Immobilienmakler","Fitnessstudio","Einzelhandel","Unternehmensberatung","Zahnarztpraxis","Autohaus","Bauunternehmen"],search_keyword_variants:{"Lokale Dienstleister":["Handwerksbetrieb","Arztpraxis","Restaurant","Fitnessstudio"],"Beratung":["Steuerberater","Rechtsanwalt","Unternehmensberatung"],"Handel":["Einzelhandel","Autohaus","Hotel"]},negative_keywords:["privat","hobby","gratis","job","karriere","ehrenamt"],bad_fit_signals:["privat","hobby","gratis","job","ehrenamt"],scoring_signals:["lokal","dienstleister","praxis","kanzlei","hotel","shop","restaurant","handwerk","immobilien"],query_priority:["Handwerksbetrieb","Arztpraxis","Restaurant","Steuerberater","Hotel","Fitnessstudio","Einzelhandel"],ideal_customer_profiles:["lokal sichtbarkeitsabhängig","schwache Website","Leadbedarf"],google_place_types:["doctor","lawyer","restaurant","gym","car_dealer","accounting"]},
  {industry_id:"personal_zeitarbeit",label:"Personal / Zeitarbeit",sort_order:18,status:"production_ready",profile_group:"IT & Beratung",aliases:["Zeitarbeit","Personal","Personalvermittlung","Leiharbeit","Arbeitnehmerüberlassung","Recruiting"],own_services:["Zeitarbeit","Personalvermittlung","Recruiting","Arbeitnehmerüberlassung","Fachkräftevermittlung","Aushilfspersonal","Industriepersonal","Pflegepersonal","Logistikpersonal"],target_customer_types:["Logistikunternehmen","Industriebetriebe","Produktionsbetriebe","Pflegeheime","Hotels","Gastronomie","Bauunternehmen","Lagerbetriebe","Reinigungsunternehmen","Einzelhandel","Callcenter"],excluded_customer_types:["Jobsuchende","Bewerber","Privatpersonen","Vereine"],searchable_business_categories:["Logistikunternehmen","Industrieunternehmen","Produktionsbetrieb","Pflegeheim","Hotel","Gastronomie","Bauunternehmen","Lagerbetrieb","Reinigungsunternehmen","Einzelhandel","Callcenter"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Produktionsbetrieb","Maschinenbau"],"Logistik":["Logistikunternehmen","Lagerbetrieb","Spedition"],"Pflege":["Pflegeheim","Seniorenheim","Klinik","Pflegedienst"],"Gastronomie":["Hotel","Gastronomie","Restaurant"]},negative_keywords:["bewerbung","jobs","stellenangebot","karriere","ausbildung","praktikum","job suche"],bad_fit_signals:["bewerbung","job","karriere","praktikum","stellengesuch","jobsuche"],scoring_signals:["produktion","logistik","pflege","hotel","schicht","lager","personalbedarf","industrie"],query_priority:["Logistikunternehmen","Industrieunternehmen","Pflegeheim","Produktionsbetrieb","Hotel","Gastronomie"],ideal_customer_profiles:["hoher Personalbedarf","Schichtbetrieb","saisonaler Bedarf"],google_place_types:["storage","lodging","hospital","restaurant"]},
  {industry_id:"buchhaltung_steuernahe_dienste",label:"Buchhaltung / steuernahe Dienste",sort_order:19,status:"production_ready",profile_group:"IT & Beratung",aliases:["Buchhaltung","Rechnungswesen","Lohnbuchhaltung","Controlling","Bilanzbuchhaltung","Büroservice"],own_services:["Buchhaltung","Lohnbuchhaltung","Belegsortierung","Rechnungswesen","Controlling","Büroservice","vorbereitende Buchhaltung","Finanzorganisation"],target_customer_types:["Kleinunternehmen","Handwerksbetriebe","Gastronomie","Einzelhandel","Startups","Freiberufler","Pflegedienste","Immobilienverwaltungen","Agenturen","Dienstleister"],excluded_customer_types:["Privatpersonen","Jobs","Vereine ohne Budget"],searchable_business_categories:["Handwerksbetrieb","Restaurant","Einzelhandel","Pflegedienst","Immobilienverwaltung","Agentur","Dienstleister","Gastronomie","Unternehmensberatung","Bauunternehmen"],search_keyword_variants:{"Lokale Unternehmen":["Handwerksbetrieb","Restaurant","Einzelhandel","Gastronomie"],"Dienstleister":["Agentur","Pflegedienst","Immobilienverwaltung"],"Beratung":["Unternehmensberatung","Dienstleister","Bauunternehmen"]},negative_keywords:["privat","job","karriere","ausbildung","kostenlos","forum"],bad_fit_signals:["privat","forum","job","kostenlos","selbst"],scoring_signals:["unternehmen","handel","handwerk","agentur","shop","dienstleister","pflege","büro"],query_priority:["Handwerksbetrieb","Restaurant","Einzelhandel","Pflegedienst","Agentur","Immobilienverwaltung"],ideal_customer_profiles:["laufende Belege","regelmäßige Buchführungspflicht"],google_place_types:["restaurant","car_repair","doctor"]},
  {industry_id:"industrieservice",label:"Industrieservice",sort_order:20,status:"production_ready",profile_group:"Industrie & Technik",aliases:["Industriereinigung","Maschinenreinigung","Industriewartung","Anlagenservice","Technikservice"],own_services:["Maschinenreinigung","Industriewartung","Anlagenservice","Werkshallenreinigung","Produktionsunterstützung","Technischer Service","Instandhaltung","Sonderreinigung"],target_customer_types:["Produktionsbetriebe","Maschinenbauunternehmen","Metallbauunternehmen","Logistikzentren","Chemiebetriebe","Lebensmittelproduktion","Industrieparks","Werkshallen","Automobilzulieferer","Kunststoffverarbeitung"],excluded_customer_types:["Privatpersonen","kleine Werkstätten ohne Budget","Jobs"],searchable_business_categories:["Produktionsbetrieb","Maschinenbau","Metallbau","Logistikzentrum","Chemiebetrieb","Lebensmittelhersteller","Industriepark","Automobilzulieferer","Kunststoffverarbeitung","Industrieunternehmen"],search_keyword_variants:{"Produktion":["Produktionsbetrieb","Industrieunternehmen","Lebensmittelhersteller"],"Technik":["Maschinenbau","Metallbau","Kunststoffverarbeitung","Automobilzulieferer"],"Standorte":["Industriepark","Logistikzentrum","Chemiebetrieb"]},negative_keywords:["privat","job","karriere","ausbildung","hobbywerkstatt"],bad_fit_signals:["privat","hobby","job","klein","werkstatt privat"],scoring_signals:["produktion","industrie","maschine","anlage","werk","halle","wartung","technik"],query_priority:["Produktionsbetrieb","Industrieunternehmen","Maschinenbau","Logistikzentrum","Metallbau","Lebensmittelhersteller"],ideal_customer_profiles:["laufende Produktion","technische Anlagen","Schichtbetrieb"],google_place_types:["storage","moving_company"]},
  {industry_id:"fuhrparkservice_fahrzeugpflege",label:"Fuhrparkservice / Fahrzeugpflege",sort_order:21,own_services:["Fahrzeugpflege","Fuhrparkreinigung","Innenreinigung","Außenreinigung","Aufbereitung","Hol- und Bringservice","Flottenservice","Smart Repair","Reifenservice"],target_customer_types:["Autohäuser","Taxiunternehmen","Pflegedienste","Handwerksbetriebe","Logistikunternehmen","Speditionen","Mietwagenfirmen","Fahrschulen","Flottenbetreiber","Lieferdienste","Kommunale Betriebe"],excluded_customer_types:["Privatfahrzeuge","Einmalige Kleinaufträge","Kleinanzeigen","Jobs"],searchable_business_categories:["Autohaus","Taxiunternehmen","Pflegedienst","Handwerksbetrieb","Logistikunternehmen","Spedition","Mietwagenfirma","Fahrschule","Lieferdienst","Kommunaler Betrieb","Fuhrparkbetrieb"],search_keyword_variants:{"Flotte":["Taxiunternehmen","Pflegedienst","Lieferdienst","Mietwagenfirma"],"Auto":["Autohaus","Fahrschule","Fuhrparkbetrieb"],"Gewerbe":["Handwerksbetrieb","Logistikunternehmen","Spedition"]},negative_keywords:["privat","gebrauchtwagen privat","job","kleinanzeigen","selber reinigen","auto privat verkaufen"],bad_fit_signals:["privat","kleinanzeige","job","einzelfahrzeug","gebrauchtwagen privat"],scoring_signals:["flotte","fahrzeuge","lieferung","taxi","pflege","autohaus","logistik","fuhrpark"],query_priority:["Autohaus","Taxiunternehmen","Logistikunternehmen","Handwerksbetrieb","Pflegedienst","Mietwagenfirma"],ideal_customer_profiles:["mehrere Fahrzeuge","regelmäßige Reinigung","Flotte"],google_place_types:["car_dealer","taxi_stand","car_rental"]},
  {industry_id:"pflege_betreuung",label:"Pflege / Betreuung",sort_order:22,own_services:["Pflege","Betreuung","Alltagsbegleitung","Seniorenbetreuung","Ambulante Pflege","Haushaltshilfe","Entlastungsleistungen","Demenzbetreuung"],target_customer_types:["Pflegeheime","Seniorenresidenzen","Betreutes Wohnen","Kliniken","Reha-Zentren","Sozialdienste","Betreuungsvereine","Ärztehäuser","Pflegedienste","Kommunale Sozialstellen"],excluded_customer_types:["Privatpersonen ohne Leistungsrahmen","Jobs","Foren","Selbsthilfe ohne Budget"],searchable_business_categories:["Pflegeheim","Seniorenresidenz","Betreutes Wohnen","Klinik","Reha Zentrum","Sozialdienst","Betreuungsverein","Ärztehaus","Pflegedienst","Sozialstation"],search_keyword_variants:{"Senioren":["Pflegeheim","Seniorenresidenz","Betreutes Wohnen","Altenheim"],"Medizin":["Klinik","Reha Zentrum","Ärztehaus","Pflegedienst"],"Sozial":["Sozialdienst","Betreuungsverein","Sozialstation"]},negative_keywords:["job","karriere","ausbildung","forum","privat","erfahrung","selbsthilfe"],bad_fit_signals:["job","forum","privat","erfahrung","selbsthilfe"],scoring_signals:["pflege","senioren","betreuung","sozial","reha","klinik","wohnen","station"],query_priority:["Pflegeheim","Seniorenresidenz","Klinik","Reha Zentrum","Sozialdienst","Pflegedienst"],ideal_customer_profiles:["regelmäßiger Betreuungsbedarf","Senioren-Zielgruppe","soziale Versorgung"],google_place_types:["hospital","doctor","health"]},
  {industry_id:"schulungen_weiterbildung",label:"Schulungen / Weiterbildung",sort_order:23,own_services:["Schulungen","Weiterbildung","Seminare","Mitarbeiterschulung","Arbeitssicherheit","Verkaufstraining","IT-Schulung","Führungskräftetraining","Pflichtunterweisungen"],target_customer_types:["Unternehmen","Industriebetriebe","Pflegeheime","Hotels","Logistikunternehmen","Handwerksbetriebe","Bildungsträger","Kommunen","Schulen","Einzelhandel","Callcenter"],excluded_customer_types:["Privatpersonen","Schülernachhilfe privat","Hobbykurse","Jobs"],searchable_business_categories:["Industrieunternehmen","Pflegeheim","Hotel","Logistikunternehmen","Handwerksbetrieb","Bildungsträger","Schule","Einzelhandel","Callcenter","Unternehmensberatung","Produktionsbetrieb"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Logistikunternehmen","Produktionsbetrieb"],"Sozial":["Pflegeheim","Hotel","Einzelhandel","Callcenter"],"Öffentlich":["Bildungsträger","Schule","Handwerksbetrieb"]},negative_keywords:["privat","nachhilfe","hobby","job","karriere","kostenlos"],bad_fit_signals:["privat","nachhilfe","hobby","job","kostenlos"],scoring_signals:["mitarbeiter","schulung","industrie","pflege","logistik","compliance","unternehmen","betrieb"],query_priority:["Industrieunternehmen","Pflegeheim","Hotel","Logistikunternehmen","Handwerksbetrieb","Bildungsträger"],ideal_customer_profiles:["mehrere Mitarbeitende","Schulungspflicht","Compliance"],google_place_types:["school","hospital","lodging"]},

  {industry_id:"dachdecker",label:"Dachdecker",sort_order:24,own_services:["Dachdeckerarbeiten","Dachreparatur","Dachsanierung","Dachabdichtung","Flachdach","Steildach","Dachrinnenreinigung","Wärmedämmung Dach","Dachfenster","Solarvorbereitung Dach"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Hotels","Wohnungsbaugesellschaften","Industriebetriebe","Gewerbeimmobilien","Bürogebäude","Pflegeheime","Schulen","Kommunen"],excluded_customer_types:["Privathaushalte","Kleinstaufträge","Jobs","DIY-Anfragen"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Hotel","Wohnungsbaugesellschaft","Industrieunternehmen","Bürogebäude","Pflegeheim","Schule","Gewerbeimmobilie"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Gewerbe":["Hotel","Bürogebäude","Industrieunternehmen","Gewerbeimmobilie"],"Sozial":["Pflegeheim","Schule","Kita"]},negative_keywords:["privat","job","karriere","ausbildung","diy","selbst"],bad_fit_signals:["privat","diy","job","einzeleigentümer","hobby"],scoring_signals:["dach","objekt","wohnanlage","verwaltung","gewerbe","sanierung","instandhaltung","bestand"],query_priority:["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft","Hotel","Industrieunternehmen"],ideal_customer_profiles:["großer Dachbestand","laufende Sanierung","Instandhaltungsvertrag"],google_place_types:["property_management_company","lodging","school"]},

  {industry_id:"geruestbau",label:"Gerüstbau",sort_order:25,own_services:["Gerüstaufbau","Gerüstvermietung","Fassadengerüst","Raumgerüst","Wetterschutz","Gerüst Abriss","Industriegerüst","Sondergerüst"],target_customer_types:["Bauunternehmen","Dachdecker","Maler","Fassadenbauer","Immobilienverwaltungen","Industriebetriebe","Hausverwaltungen","Generalunternehmer","Architekten"],excluded_customer_types:["Privathaushalte","Kleinstaufträge","Jobs"],searchable_business_categories:["Bauunternehmen","Dachdecker","Malerbetrieb","Fassadenbauer","Immobilienverwaltung","Industrieunternehmen","Generalunternehmer","Architekturbüro"],search_keyword_variants:{"Bau":["Bauunternehmen","Generalunternehmer","Baufirma"],"Handwerk":["Dachdecker","Malerbetrieb","Fassadenbauer"],"Industrie":["Industrieunternehmen","Produktionsbetrieb"]},negative_keywords:["privat","job","ausbildung","kleinauftrag","hobby"],bad_fit_signals:["privat","job","hobby","kleinauftrag"],scoring_signals:["bau","fassade","sanierung","industrie","objekt","außen","projekt"],query_priority:["Bauunternehmen","Dachdecker","Malerbetrieb","Industrieunternehmen","Immobilienverwaltung"],ideal_customer_profiles:["Bauprojekte","regelmäßige Fassadenarbeiten","Industriewartung"],google_place_types:["general_contractor","roofing_contractor"]},

  {industry_id:"trockenbau_innenausbau",label:"Trockenbau / Innenausbau",sort_order:26,own_services:["Trockenbau","Innenausbau","Wandsysteme","Deckenabhängungen","Akustikdecken","Brandschutzwände","Glastrennwände","Estrich","Bodenaufbau","Büroausbau"],target_customer_types:["Bauunternehmen","Immobilienverwaltungen","Hotels","Bürogebäude","Einzelhandel","Praxen","Hausverwaltungen","Generalunternehmer","Projektentwickler"],excluded_customer_types:["Privathaushalte","Kleinstaufträge","Jobs"],searchable_business_categories:["Bauunternehmen","Hotel","Bürogebäude","Einzelhandel","Arztpraxis","Immobilienverwaltung","Generalunternehmer","Projektentwickler"],search_keyword_variants:{"Bau":["Bauunternehmen","Generalunternehmer","Projektentwickler"],"Gewerbe":["Hotel","Bürogebäude","Einzelhandel"]},negative_keywords:["privat","job","diy","hobby","kleinauftrag"],bad_fit_signals:["privat","diy","job","hobby"],scoring_signals:["büro","ausbau","umbau","renovierung","gewerbe","projekt","bau","innen"],query_priority:["Bauunternehmen","Hotel","Bürogebäude","Einzelhandel","Projektentwickler"],ideal_customer_profiles:["Büro-/Gewerbeausbau","Hotelsanierung","laufende Bauprojekte"],google_place_types:["general_contractor","lodging"]},

  {industry_id:"fliesenleger",label:"Fliesenleger",sort_order:27,own_services:["Fliesenlegen","Badezimmer","Küchenfliesen","Terrassenfliesen","Großformat","Feuchtraumabdichtung","Naturstein","Fliesen Gewerbeflächen","Verfugen","Sanierung"],target_customer_types:["Hausverwaltungen","Hotels","Bauunternehmen","Pflegeheime","Bürogebäude","Gastronomiebetriebe","Schwimmbäder","Praxen","Wohnungsbaugesellschaften"],excluded_customer_types:["Privathaushalte","Kleinstaufträge","DIY","Jobs"],searchable_business_categories:["Hausverwaltung","Hotel","Bauunternehmen","Pflegeheim","Restaurant","Schwimmbad","Arztpraxis","Wohnungsbaugesellschaft"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Wohnungsbaugesellschaft"],"Gewerbe":["Hotel","Restaurant","Schwimmbad"],"Bau":["Bauunternehmen","Generalunternehmer"]},negative_keywords:["privat","job","diy","selbst verlegen","kleinauftrag"],bad_fit_signals:["privat","diy","job","selbst"],scoring_signals:["fliesen","bad","nasszelle","gewerbe","hotel","bau","renovierung"],query_priority:["Hausverwaltung","Hotel","Bauunternehmen","Pflegeheim","Restaurant"],ideal_customer_profiles:["Gewerbe-Bäder","Hotel-Renovierung","Pflegeheime mit Hygienestandards"],google_place_types:["lodging","hospital","restaurant","swimming_pool"]},

  {industry_id:"bodenleger",label:"Bodenleger",sort_order:28,own_services:["Bodenbeläge","Laminat","Parkett","Vinyl","Teppich gewerblich","Epoxidboden","Industrieboden","Sportboden","Estrich","Bodenbeschichtung"],target_customer_types:["Hausverwaltungen","Bürogebäude","Hotels","Industriebetriebe","Praxen","Einzelhandel","Pflegeheime","Schulen","Kitas","Bauunternehmen"],excluded_customer_types:["Privathaushalte","Kleinstaufträge","Jobs","DIY"],searchable_business_categories:["Hausverwaltung","Bürogebäude","Hotel","Industrieunternehmen","Arztpraxis","Einzelhandel","Pflegeheim","Schule","Kita"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung"],"Gewerbe":["Bürogebäude","Hotel","Einzelhandel"],"Industrie":["Industrieunternehmen","Produktionsbetrieb"]},negative_keywords:["privat","job","diy","hobby","kleinauftrag"],bad_fit_signals:["privat","diy","job","hobby"],scoring_signals:["boden","fläche","gewerbe","büro","hotel","industrie","renovierung"],query_priority:["Hausverwaltung","Bürogebäude","Hotel","Industrieunternehmen","Pflegeheim"],ideal_customer_profiles:["große Gewerbeflächen","Hotel-Sanierung","Industrieböden"],google_place_types:["lodging","hospital","school","general_contractor"]},

  {industry_id:"schluesseldienst_schliesanlagen",label:"Schlüsseldienst / Schließanlagen",sort_order:29,own_services:["Schließanlagen","Zylinder","Schlüsseldienst","Zutrittskontrolle","Masterkey","Codeschlösser","Elektronische Schlösser","Notöffnung gewerblich","Türsicherung","Tresore"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Hotels","Bürogebäude","Pflegeheime","Schulen","Kitas","Industriebetriebe","Einzelhandel","Wohnungsbaugesellschaften"],excluded_customer_types:["Privatöffnungen","Einmalige Notfälle ohne Abo","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Hotel","Bürogebäude","Pflegeheim","Schule","Industrieunternehmen","Einzelhandel","Wohnungsbaugesellschaft"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Gewerbe":["Hotel","Bürogebäude","Einzelhandel"],"Sozial":["Pflegeheim","Schule","Kita"]},negative_keywords:["privat","job","ausbildung","notfall privat"],bad_fit_signals:["privat","job","notfall einzeln"],scoring_signals:["schließanlage","sicherheit","zugang","verwaltung","objekt","schlüssel","gewerbe"],query_priority:["Hausverwaltung","Immobilienverwaltung","Hotel","Bürogebäude","Pflegeheim"],ideal_customer_profiles:["Großobjekte","mehrere Mieter","Zutrittskontrolle komplex"],google_place_types:["property_management_company","lodging","school"]},

  {industry_id:"schaedlingsbekaempfung",label:"Schädlingsbekämpfung",sort_order:30,own_services:["Schädlingsbekämpfung","Kammerjäger","Rattenbekämpfung","Insektenbekämpfung","Vorsorgevertrag","Monitoring","Fliegenbekämpfung","Taubenabwehr","Mäusebekämpfung","HACCP Kontrolle"],target_customer_types:["Hausverwaltungen","Lebensmittelhersteller","Restaurants","Hotels","Schulen","Kitas","Pflegeheime","Lagerhallen","Produktionsbetriebe","Einzelhandel","Supermärkte"],excluded_customer_types:["Privatwohnungen ohne Vertrag","Jobs","Einmalige Kleinstaufträge"],searchable_business_categories:["Hausverwaltung","Lebensmittelhersteller","Restaurant","Hotel","Schule","Kindertagesstätte","Pflegeheim","Lagerhalle","Produktionsbetrieb","Einzelhandel","Supermarkt"],search_keyword_variants:{"Lebensmittel":["Lebensmittelhersteller","Restaurant","Hotel","Supermarkt"],"Sozial":["Schule","Kita","Pflegeheim"],"Lager":["Lagerhalle","Produktionsbetrieb"]},negative_keywords:["privat","job","einmalig privat","diy","selbst"],bad_fit_signals:["privat","job","diy","einmalig"],scoring_signals:["hygiene","haccp","lebensmittel","lager","gastronomie","gewerbe","objekt","befall"],query_priority:["Lebensmittelhersteller","Restaurant","Hotel","Hausverwaltung","Supermarkt"],ideal_customer_profiles:["HACCP-pflichtige Betriebe","Gastronomie","Lebensmittelverarbeitung"],google_place_types:["restaurant","lodging","school","food"]},

  {industry_id:"brandschutzservice",label:"Brandschutzservice",sort_order:31,own_services:["Feuerlöscher-Service","Brandschutzbegehung","Fluchtwegschilder","Brandmeldeanlage","Sprinkleranlage","Brandschutzschulung","BSB-Maßnahmen","Feuerlöscher-Prüfung","Notausgangssysteme"],target_customer_types:["Industriebetriebe","Hotels","Bürogebäude","Hausverwaltungen","Pflegeheime","Schulen","Einkaufszentren","Produktionsbetriebe","Lagerbetriebe","Gesundheitszentren"],excluded_customer_types:["Privathaushalte","Jobs","Kleinstaufträge"],searchable_business_categories:["Industrieunternehmen","Hotel","Bürogebäude","Hausverwaltung","Pflegeheim","Schule","Einkaufszentrum","Produktionsbetrieb","Lagerbetrieb"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Produktionsbetrieb","Lagerbetrieb"],"Gewerbe":["Hotel","Bürogebäude","Einkaufszentrum"],"Sozial":["Pflegeheim","Schule","Kita"]},negative_keywords:["privat","job","ausbildung","hobby"],bad_fit_signals:["privat","job","hobby"],scoring_signals:["brandschutz","pflicht","wartung","gewerbe","industrie","behörde","feuerwehr","objekt"],query_priority:["Industrieunternehmen","Hotel","Bürogebäude","Pflegeheim","Schule"],ideal_customer_profiles:["gesetzliche Prüfpflicht","mehrere Stockwerke","laufender Wartungsvertrag"],google_place_types:["lodging","hospital","shopping_mall","school"]},

  {industry_id:"aufzugservice",label:"Aufzugservice",sort_order:32,own_services:["Aufzugwartung","Aufzugprüfung","Aufzugreparatur","TÜV-Abnahme","Aufzugmodernisierung","Plattformlifte","Treppenlift","Lastenlift","Aufzug Notdienst","Aufzug Inspektion"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Hotels","Pflegeheime","Bürogebäude","Wohnungsbaugesellschaften","Kaufhäuser","Krankenhäuser","Schulen"],excluded_customer_types:["Privathaushalte ohne Aufzug","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Hotel","Pflegeheim","Bürogebäude","Wohnungsbaugesellschaft","Kaufhaus","Krankenhaus","Schule"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Gewerbe":["Hotel","Bürogebäude","Kaufhaus"],"Medizin":["Krankenhaus","Klinik","Pflegeheim"]},negative_keywords:["privat","job","treppenlift privat","ausbildung"],bad_fit_signals:["privat","job","einzelne person"],scoring_signals:["aufzug","fahrstuhl","wartung","pflicht","tuev","prüfung","gewerbe","objekt"],query_priority:["Hausverwaltung","Immobilienverwaltung","Hotel","Pflegeheim","Bürogebäude"],ideal_customer_profiles:["mehrere Aufzüge","Wartungsvertrag","TÜV-pflichtig"],google_place_types:["property_management_company","lodging","hospital","shopping_mall"]},

  {industry_id:"tor_tuertechnik",label:"Tor- und Türtechnik",sort_order:33,own_services:["Tore","Sektionaltore","Rolltore","Brandschutztüren","Industrietore","Einfahrtstore","Schrankenanlagen","Torwartung","Türantriebe","Garagentore gewerblich"],target_customer_types:["Industriebetriebe","Lagerhallen","Logistikzentren","Hausverwaltungen","Gewerbeimmobilien","Hotels","Parkhäuser","Einzelhandel","Produktionsbetriebe"],excluded_customer_types:["Privathaushalte","Kleinstaufträge","Jobs"],searchable_business_categories:["Industrieunternehmen","Lagerhalle","Logistikzentrum","Hausverwaltung","Gewerbeimmobilie","Hotel","Parkhaus","Einzelhandel","Produktionsbetrieb"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Produktionsbetrieb","Lagerhalle"],"Logistik":["Logistikzentrum","Spedition","Lagerbetrieb"],"Gewerbe":["Hotel","Einzelhandel","Parkhaus"]},negative_keywords:["privat","job","garagentor privat","hobby"],bad_fit_signals:["privat","job","hobby"],scoring_signals:["tor","gewerbe","industrie","lager","logistik","wartung","feuerschutz","schranke"],query_priority:["Industrieunternehmen","Lagerhalle","Logistikzentrum","Hausverwaltung","Gewerbeimmobilie"],ideal_customer_profiles:["Industriehallen","Lagerbetriebe","laufende Wartung"],google_place_types:["storage","moving_company","shopping_mall"]},

  {industry_id:"photovoltaik_service",label:"Photovoltaik-Service",sort_order:34,own_services:["PV-Anlage Wartung","Solarreinigung","PV-Monitoring","Ertragsmessung","Defektanalyse","Wechselrichter-Service","Batteriespeicher","PV-Inspektion","Thermografie","PV-Reinigung"],target_customer_types:["Industriebetriebe","Gewerbehallen","Landwirtschaft","Hotels","Einkaufszentren","Bürogebäude","Pflegeheime","Schulen","Logistikzentren","Gemeinden"],excluded_customer_types:["Privathaushalte","Kleinstanlagen","Jobs"],searchable_business_categories:["Industrieunternehmen","Gewerbehalle","Landwirtschaft","Hotel","Einkaufszentrum","Bürogebäude","Pflegeheim","Schule","Logistikzentrum"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Gewerbehalle","Logistikzentrum"],"Gewerbe":["Hotel","Einkaufszentrum","Bürogebäude"],"Agrar":["Landwirtschaft","Agrarhandel","Landwirt"]},negative_keywords:["privat","job","eigenheim","ausbildung","diy"],bad_fit_signals:["privat","eigenheim","job","diy"],scoring_signals:["solar","pv","energie","gewerbe","dach","industrie","ertrag","anlage"],query_priority:["Industrieunternehmen","Gewerbehalle","Hotel","Landwirtschaft","Einkaufszentrum"],ideal_customer_profiles:["große Dachflächen","Gewerbe/Industrie","laufender Wartungsvertrag"],google_place_types:["storage","shopping_mall","lodging"]},

  {industry_id:"umzugsunternehmen",label:"Umzugsunternehmen",sort_order:35,own_services:["Gewerbeumzug","Büroumzug","IT-Umzug","Möbeldemontage/-montage","Einlagerung","Aktenumzug","Messetransport","Praxisumzug","Archivumzug","Küchenmontage"],target_customer_types:["Unternehmen","Bürogebäude","Arztpraxen","Kanzleien","Hotels","Pflegeheime","Schulen","Industriebetriebe","Hausverwaltungen"],excluded_customer_types:["Privatumzüge","Kleinstaufträge","Jobs"],searchable_business_categories:["Bürogebäude","Arztpraxis","Kanzlei","Hotel","Pflegeheim","Schule","Industrieunternehmen","Hausverwaltung"],search_keyword_variants:{"Büro":["Bürogebäude","Kanzlei","Unternehmensberatung"],"Medizin":["Arztpraxis","Zahnarztpraxis","Pflegeheim"],"Gewerbe":["Hotel","Industrieunternehmen","Schule"]},negative_keywords:["privat","privatumzug","job","karriere","ausbildung"],bad_fit_signals:["privat","job","kleinstauftrag"],scoring_signals:["büro","gewerbe","praxis","umzug","transport","lager","archiv","it"],query_priority:["Bürogebäude","Arztpraxis","Hotel","Pflegeheim","Kanzlei"],ideal_customer_profiles:["Firmenumzug","mehrere Standorte","IT-Equipment"],google_place_types:["doctor","lawyer","lodging","school"]},

  {industry_id:"druckerei_werbetechnik",label:"Druckerei / Werbetechnik",sort_order:36,own_services:["Digitaldruck","Großformat","Werbebanner","Fahrzeugbeschriftung","Beschilderung","Folienbeschriftung","Messebeschriftung","Schilder","Aufkleber","Visitenkarten"],target_customer_types:["Einzelhandel","Hotels","Gastronomie","Bauunternehmen","Handwerksbetriebe","Eventveranstalter","Autohäuser","Praxen","Rechtsanwälte","Messeveranstalter"],excluded_customer_types:["Privatpersonen","Kleinstaufträge","Jobs"],searchable_business_categories:["Einzelhandel","Hotel","Restaurant","Bauunternehmen","Handwerksbetrieb","Autohaus","Arztpraxis","Rechtsanwalt","Messeveranstalter","Eventveranstalter"],search_keyword_variants:{"Lokale Unternehmen":["Einzelhandel","Handwerksbetrieb","Restaurant"],"B2B":["Hotel","Autohaus","Bauunternehmen"],"Messe":["Messeveranstalter","Eventveranstalter"]},negative_keywords:["privat","job","hobby","gratis","ausbildung"],bad_fit_signals:["privat","job","hobby","einmalig privat"],scoring_signals:["beschriftung","marketing","werbung","flotte","messe","event","gewerbe","marke"],query_priority:["Einzelhandel","Handwerksbetrieb","Hotel","Autohaus","Bauunternehmen"],ideal_customer_profiles:["laufender Werbebedarf","Fuhrpark-Beschriftung","Messepräsenz"],google_place_types:["car_dealer","restaurant","lodging","general_contractor"]},

  {industry_id:"aktenvernichtung_dokumentenmanagement",label:"Aktenvernichtung / Dokumentenmanagement",sort_order:37,own_services:["Aktenvernichtung","DSGVO-konformes Shredding","Dattenträgervernichtung","Dokumentenarchivierung","Papiershredder-Service","Aktenentsorgung","Scanning-Service","Langzeitarchiv"],target_customer_types:["Kanzleien","Steuerberater","Arztpraxen","Banken","Versicherungen","Industriebetriebe","Hausverwaltungen","Öffentliche Verwaltung","Krankhäuser","Hotels"],excluded_customer_types:["Privatpersonen","Kleinstaufträge","Jobs"],searchable_business_categories:["Rechtsanwalt","Steuerberater","Arztpraxis","Versicherung","Industrieunternehmen","Hausverwaltung","Krankenhaus","Hotel"],search_keyword_variants:{"Kanzleien":["Rechtsanwalt","Steuerberater","Kanzlei"],"Medizin":["Arztpraxis","Zahnarztpraxis","Krankenhaus"],"Industrie":["Industrieunternehmen","Versicherung"]},negative_keywords:["privat","job","ausbildung","hobby"],bad_fit_signals:["privat","job","hobby"],scoring_signals:["dsgvo","datenschutz","akten","archiv","compliance","kanzlei","praxis","bank"],query_priority:["Rechtsanwalt","Steuerberater","Arztpraxis","Industrieunternehmen","Krankenhaus"],ideal_customer_profiles:["DSGVO-pflichtig","regelmäßige Aktenmengen","mehrere Standorte"],google_place_types:["lawyer","accounting","doctor","hospital"]},

  {industry_id:"energieberatung",label:"Energieberatung",sort_order:38,own_services:["Energieberatung","Energieaudit","Verbrauchsanalyse","Einsparpotenzial","Fördermittelberatung","ISO 50001","Wärmebildkamera","Sanierungsberatung","Energieausweis Gewerbe"],target_customer_types:["Industriebetriebe","Hotels","Bürogebäude","Hausverwaltungen","Pflegeheime","Produktionsbetriebe","Einkaufszentren","Kommunen","Logistikzentren"],excluded_customer_types:["Privathaushalte","Jobs","Kleinstaufträge"],searchable_business_categories:["Industrieunternehmen","Hotel","Bürogebäude","Hausverwaltung","Pflegeheim","Produktionsbetrieb","Einkaufszentrum","Logistikzentrum"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Produktionsbetrieb","Logistikzentrum"],"Gewerbe":["Hotel","Bürogebäude","Einkaufszentrum"],"Sozial":["Pflegeheim","Schule","Verwaltung"]},negative_keywords:["privat","job","eigenheim","hobby"],bad_fit_signals:["privat","job","eigenheim"],scoring_signals:["energie","verbrauch","strom","gas","kosten","einsparung","audit","gewerbe","industrie"],query_priority:["Industrieunternehmen","Hotel","Bürogebäude","Produktionsbetrieb","Hausverwaltung"],ideal_customer_profiles:["hoher Energieverbrauch","gesetzliche Audit-Pflicht","Sanierungsbedarf"],google_place_types:["lodging","shopping_mall","storage"]},

  {industry_id:"arbeitsschutz_arbeitssicherheit",label:"Arbeitsschutz / Arbeitssicherheit",sort_order:39,own_services:["Arbeitssicherheit","Gefährdungsbeurteilung","SIFA","Begehungen","Unterweisungen","Schutzausrüstung","UVV-Prüfung","Brandschutzbeauftragter","Ersthelfer-Schulung","Sicherheitsdokumentation"],target_customer_types:["Industriebetriebe","Handwerksbetriebe","Produktionsbetriebe","Bauunternehmen","Lagerbetriebe","Hotels","Pflegeheime","Praxen","Gastronomie","Schulen"],excluded_customer_types:["Privatpersonen","Jobs","Vereine ohne Budget"],searchable_business_categories:["Industrieunternehmen","Handwerksbetrieb","Produktionsbetrieb","Bauunternehmen","Lagerbetrieb","Hotel","Pflegeheim","Arztpraxis","Restaurant"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Produktionsbetrieb","Bauunternehmen"],"Handwerk":["Handwerksbetrieb","Lagerbetrieb"],"Sozial":["Pflegeheim","Hotel","Gastronomie"]},negative_keywords:["privat","job","hobby","ausbildung"],bad_fit_signals:["privat","job","hobby"],scoring_signals:["sicherheit","pflicht","uvv","gewerbe","industrie","begehung","arbeitsplatz","gefährdung"],query_priority:["Industrieunternehmen","Bauunternehmen","Handwerksbetrieb","Produktionsbetrieb","Hotel"],ideal_customer_profiles:["gesetzliche Pflicht","mehrere Mitarbeitende","Produktionsbetrieb"],google_place_types:["general_contractor","lodging","hospital","restaurant"]},

  {industry_id:"datenschutz_compliance",label:"Datenschutz / Compliance",sort_order:40,own_services:["Datenschutzbeauftragter extern","DSGVO-Beratung","Datenschutz-Audit","Verarbeitungsverzeichnis","Mitarbeiterschulung DSGVO","Datenschutzpolicy","Compliance-Beratung","TOM-Dokumentation"],target_customer_types:["Arztpraxen","Steuerberater","Kanzleien","IT-Unternehmen","Finanzdienstleister","Versicherungen","Handwerksbetriebe","Immobilienverwaltungen","Pflegeheime","Online-Shops"],excluded_customer_types:["Privatpersonen","Vereine ohne Budget","Jobs"],searchable_business_categories:["Arztpraxis","Steuerberater","Rechtsanwalt","IT-Unternehmen","Versicherung","Immobilienverwaltung","Pflegeheim","Online-Händler","Handwerksbetrieb"],search_keyword_variants:{"Kanzleien":["Rechtsanwalt","Steuerberater","Kanzlei"],"Medizin":["Arztpraxis","Zahnarztpraxis","Pflegeheim"],"IT":["IT-Unternehmen","Software","Onlineshop"]},negative_keywords:["privat","job","hobby","verein"],bad_fit_signals:["privat","job","hobby","verein klein"],scoring_signals:["dsgvo","compliance","datenschutz","gesundheit","praxis","kanzlei","it","data"],query_priority:["Arztpraxis","Steuerberater","Rechtsanwalt","IT-Unternehmen","Pflegeheim"],ideal_customer_profiles:["DSGVO-pflichtig","sensible Daten","mehrere Mitarbeitende"],google_place_types:["doctor","lawyer","accounting","hospital"]},

  {industry_id:"messebau",label:"Messebau",sort_order:41,own_services:["Messestand","Standdesign","Standaufbau","Standabbau","Messemöbel","Grafik-Druck","LED-Beleuchtung","Mietstand","Fullservice Messe","Ausstellungssysteme"],target_customer_types:["Industriebetriebe","Technologieunternehmen","Agenturen","Mittelständler","Autohäuser","Pharmaunternehmen","Maschinenbauunternehmen","Messeveranstalter","Softwarehersteller"],excluded_customer_types:["Privatpersonen","Kleinstunternehmen ohne Budget","Jobs"],searchable_business_categories:["Industrieunternehmen","Technologieunternehmen","Autohaus","Pharmaunternehmen","Maschinenbau","Softwarehersteller","Unternehmensberatung","Agentur"],search_keyword_variants:{"Industrie":["Industrieunternehmen","Maschinenbau","Pharmaunternehmen"],"Technologie":["Technologieunternehmen","Softwarehersteller"],"Handel":["Autohaus","Agentur","Unternehmensberatung"]},negative_keywords:["privat","job","ausbildung","hobby","flohmarkt"],bad_fit_signals:["privat","job","hobby","flohmarkt"],scoring_signals:["messe","aussteller","stand","produkt","b2b","präsentation","brand","technik"],query_priority:["Industrieunternehmen","Maschinenbau","Technologieunternehmen","Autohaus","Agentur"],ideal_customer_profiles:["regelmäßige Messeauftritte","eigene Produkte","B2B-Vertrieb"],google_place_types:["car_dealer","general_contractor","event_venue"]},

  {industry_id:"fallback_lokaler_dienstleister",label:"Lokaler Dienstleister (Allgemein)",sort_order:90,own_services:["Dienstleistungen","Service","Beratung","Wartung","Instandhaltung"],target_customer_types:["Hausverwaltungen","Bürogebäude","Hotels","Industriebetriebe","Pflegeheime","Schulen","Einzelhandel","Praxen"],excluded_customer_types:["Privatpersonen","Jobs"],searchable_business_categories:["Hausverwaltung","Bürogebäude","Hotel","Industrieunternehmen","Pflegeheim","Schule","Einzelhandel","Arztpraxis"],search_keyword_variants:{"Allgemein":["Hausverwaltung","Bürogebäude","Hotel","Einzelhandel"]},negative_keywords:["privat","job","hobby","ausbildung"],bad_fit_signals:["privat","job","hobby"],scoring_signals:["gewerbe","objekt","verwaltung","unternehmen","betrieb","büro","standort"],query_priority:["Hausverwaltung","Bürogebäude","Hotel","Industrieunternehmen"],ideal_customer_profiles:["lokaler B2B-Bedarf","regelmäßige Dienstleistung"],google_place_types:["property_management_company","lodging","school"]},

  {industry_id:"fallback_handwerk_allgemein",label:"Handwerksbetrieb (Allgemein)",sort_order:91,own_services:["Handwerksleistungen","Reparatur","Wartung","Montage","Installation","Instandhaltung"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","Hotels","Bürogebäude","Wohnungsbaugesellschaften","Industriebetriebe"],excluded_customer_types:["Privathaushalte","Jobs","Kleinstaufträge"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","Hotel","Bürogebäude","Wohnungsbaugesellschaft","Industrieunternehmen"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","Wohnungsbaugesellschaft"],"Gewerbe":["Hotel","Bürogebäude","Industrieunternehmen"]},negative_keywords:["privat","job","diy","hobby"],bad_fit_signals:["privat","diy","job","hobby"],scoring_signals:["verwaltung","objekt","gewerbe","instandhaltung","handwerk","reparatur"],query_priority:["Hausverwaltung","Immobilienverwaltung","Hotel","Bürogebäude"],ideal_customer_profiles:["regelmäßiger Instandhaltungsbedarf","mehrere Objekte"],google_place_types:["property_management_company","lodging"]},

  {industry_id:"fallback_b2b_service",label:"B2B-Service (Allgemein)",sort_order:92,own_services:["B2B-Dienstleistung","Unternehmensservice","Beratung","Projektarbeit","Outsourcing"],target_customer_types:["Mittelständler","KMU","Industriebetriebe","Bürogebäude","Hotels","Praxen"],excluded_customer_types:["Privatpersonen","Jobs"],searchable_business_categories:["Industrieunternehmen","Bürogebäude","Hotel","Unternehmensberatung","Arztpraxis","Handwerksbetrieb"],search_keyword_variants:{"KMU":["Unternehmensberatung","Handwerksbetrieb","Bürogebäude"],"Industrie":["Industrieunternehmen","Produktionsbetrieb"]},negative_keywords:["privat","job","hobby","ausbildung"],bad_fit_signals:["privat","job","hobby"],scoring_signals:["unternehmen","betrieb","gewerbe","b2b","service","dienstleister"],query_priority:["Industrieunternehmen","Bürogebäude","Hotel","Unternehmensberatung"],ideal_customer_profiles:["regelmäßiger B2B-Bedarf","Gewerbekunden"],google_place_types:["general_contractor","lodging","doctor"]},

  {industry_id:"fallback_immobiliennaher_dienstleister",label:"Immobiliennaher Dienstleister",sort_order:93,own_services:["Objektservice","Immobilienservice","Verwaltungsunterstützung","Objektpflege","Instandhaltung"],target_customer_types:["Hausverwaltungen","Immobilienverwaltungen","WEG-Verwaltungen","Wohnungsbaugesellschaften","Property Management Firmen"],excluded_customer_types:["Privathaushalte","Jobs"],searchable_business_categories:["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Wohnungsbaugesellschaft","Property Management"],search_keyword_variants:{"Verwaltung":["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Wohnungsbaugesellschaft"]},negative_keywords:["privat","job","mietgesuch","wohnung gesucht"],bad_fit_signals:["privat","mietgesuch","job","einzeleigentümer"],scoring_signals:["verwaltung","objekt","weg","bestand","wohnanlage","immobilien"],query_priority:["Hausverwaltung","Immobilienverwaltung","WEG Verwaltung","Wohnungsbaugesellschaft"],ideal_customer_profiles:["Objektbestand","mehrere Einheiten","laufende Betreuung"],google_place_types:["property_management_company","real_estate_agency"]},

  {industry_id:"fallback_gesundheitsnaher_dienstleister",label:"Gesundheitsnaher Dienstleister",sort_order:94,own_services:["Gesundheitsnahe Dienstleistung","Praxisservice","Pflege-Support","Medizinnaher Service"],target_customer_types:["Arztpraxen","Zahnarztpraxen","Pflegeheime","Kliniken","Therapiezentren","Apotheken","Gesundheitszentren"],excluded_customer_types:["Privatpersonen","Jobs","Foren"],searchable_business_categories:["Arztpraxis","Zahnarztpraxis","Pflegeheim","Klinik","Therapiezentrum","Apotheke"],search_keyword_variants:{"Praxis":["Arztpraxis","Zahnarztpraxis","Ärztehaus"],"Pflege":["Pflegeheim","Seniorenheim","Klinik"],"Therapie":["Therapiezentrum","Physiotherapie"]},negative_keywords:["privat","job","forum","selbsthilfe","hobby"],bad_fit_signals:["privat","job","forum","selbsthilfe"],scoring_signals:["praxis","gesundheit","pflege","medizin","therapie","klinik","zentrum"],query_priority:["Arztpraxis","Zahnarztpraxis","Pflegeheim","Klinik","Therapiezentrum"],ideal_customer_profiles:["professioneller Gesundheitsbetrieb","Patientenverkehr"],google_place_types:["doctor","dentist","hospital","pharmacy","physiotherapist"]}
];

const TAXONOMY_VERSION = "v4-db-2026-05";

// ── Helpers ──────────────────────────────────────────────────────────────────

function computeHash(entry) {
  // Simple deterministic hash der relevanten Felder für Sync-Validierung
  const relevant = [
    entry.industry_id,
    entry.label,
    entry.target_customer_types,
    entry.searchable_business_categories,
    entry.search_keyword_variants,
    entry.negative_keywords,
    entry.scoring_signals,
    entry.query_priority,
  ].map(v => typeof v === 'object' ? JSON.stringify(v) : String(v || '')).join('|');
  // FNV-1a 32-bit hash (keine Crypto-API nötig)
  let hash = 0x811c9dc5;
  for (let i = 0; i < relevant.length; i++) {
    hash ^= relevant.charCodeAt(i);
    hash = (hash * 0x01000193) >>> 0;
  }
  return hash.toString(16).padStart(8, '0');
}

function parseJsonField(val, fallback = []) {
  if (!val) return fallback;
  if (Array.isArray(val) || typeof val === 'object') return val;
  try { return JSON.parse(val); } catch { return fallback; }
}

function dbEntryToProfile(entry) {
  return {
    id: entry.industry_id,
    label: entry.label,
    sort_order: entry.sort_order || 99,
    status: entry.status || 'production_ready',
    profile_group: entry.profile_group || null,
    aliases: parseJsonField(entry.aliases),
    ownServices: parseJsonField(entry.own_services),
    targetCustomerTypes: parseJsonField(entry.target_customer_types),
    excludedCustomerTypes: parseJsonField(entry.excluded_customer_types),
    searchableBusinessCategories: parseJsonField(entry.searchable_business_categories),
    searchKeywordVariants: parseJsonField(entry.search_keyword_variants, {}),
    negativeKeywords: parseJsonField(entry.negative_keywords),
    badFitSignals: parseJsonField(entry.bad_fit_signals),
    scoringSignals: parseJsonField(entry.scoring_signals),
    queryPriority: parseJsonField(entry.query_priority),
    idealCustomerProfiles: parseJsonField(entry.ideal_customer_profiles),
    googlePlaceTypes: parseJsonField(entry.google_place_types),
    content_hash: entry.content_hash,
    version: entry.version || TAXONOMY_VERSION,
  };
}

function seedEntryToDbRecord(seed) {
  return {
    industry_id: seed.industry_id,
    label: seed.label,
    version: TAXONOMY_VERSION,
    is_active: true,
    sort_order: seed.sort_order || 99,
    status: seed.status || 'production_ready',
    profile_group: seed.profile_group || null,
    aliases: JSON.stringify(seed.aliases || []),
    own_services: JSON.stringify(seed.own_services || []),
    target_customer_types: JSON.stringify(seed.target_customer_types || []),
    excluded_customer_types: JSON.stringify(seed.excluded_customer_types || []),
    searchable_business_categories: JSON.stringify(seed.searchable_business_categories || []),
    search_keyword_variants: JSON.stringify(seed.search_keyword_variants || {}),
    negative_keywords: JSON.stringify(seed.negative_keywords || []),
    bad_fit_signals: JSON.stringify(seed.bad_fit_signals || []),
    scoring_signals: JSON.stringify(seed.scoring_signals || []),
    query_priority: JSON.stringify(seed.query_priority || []),
    ideal_customer_profiles: JSON.stringify(seed.ideal_customer_profiles || []),
    google_place_types: JSON.stringify(seed.google_place_types || []),
    content_hash: computeHash(seed),
  };
}

// ── MAIN ─────────────────────────────────────────────────────────────────────

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Auth: öffentlicher Lesezugriff für Frontend-Onboarding + authenticated für Admin-Writes
    let user = null;
    try { user = await base44.auth.me(); } catch {}

    const body = await req.json().catch(() => ({}));
    const action = body.action || 'list'; // list | seed | get_single

    // ── list: alle aktiven Einträge zurückgeben ───────────────────────────────
    if (action === 'list') {
      let entries = await base44.asServiceRole.entities.TaxonomyEntry.filter(
        { is_active: true }, 'sort_order', 100
      );

      // Self-seeding: Falls DB leer, Seed-Daten einmalig schreiben
      if (entries.length === 0) {
        console.info('[getTaxonomy] DB leer – initialisiere mit Seed-Daten...');
        const createOps = TAXONOMY_SEED.map(seed =>
          base44.asServiceRole.entities.TaxonomyEntry.create(seedEntryToDbRecord(seed))
        );
        await Promise.all(createOps);
        entries = await base44.asServiceRole.entities.TaxonomyEntry.filter(
          { is_active: true }, 'sort_order', 100
        );
        console.info(`[getTaxonomy] Seed abgeschlossen: ${entries.length} Einträge`);
      }

      const profiles = entries.map(dbEntryToProfile).sort((a, b) => a.sort_order - b.sort_order);

      // Taxonomy-Hash = Hash aller Entry-Hashes (Reihenfolge nach industry_id sort)
      const allHashes = profiles.map(p => p.content_hash || '').join('');
      let taxonomyHash = 0x811c9dc5;
      for (let i = 0; i < allHashes.length; i++) {
        taxonomyHash ^= allHashes.charCodeAt(i);
        taxonomyHash = (taxonomyHash * 0x01000193) >>> 0;
      }
      const taxonomy_hash = taxonomyHash.toString(16).padStart(8, '0');

      return Response.json({
        success: true,
        version: TAXONOMY_VERSION,
        taxonomy_hash,
        count: profiles.length,
        profiles,
      });
    }

    // ── seed_reset: Seed-Daten zurückschreiben (Admin only) ──────────────────
    if (action === 'seed_reset') {
      if (!user || !['admin', 'platform_owner', 'platform_admin'].includes(user.role)) {
        return Response.json({ error: 'Admin-Zugriff erforderlich', success: false }, { status: 403 });
      }
      // Bestehende deaktivieren
      const existing = await base44.asServiceRole.entities.TaxonomyEntry.filter({}, 'sort_order', 200);
      await Promise.all(existing.map(e => base44.asServiceRole.entities.TaxonomyEntry.update(e.id, { is_active: false })));
      // Seed neu schreiben
      const createOps = TAXONOMY_SEED.map(seed =>
        base44.asServiceRole.entities.TaxonomyEntry.create(seedEntryToDbRecord(seed))
      );
      await Promise.all(createOps);
      return Response.json({ success: true, message: `${TAXONOMY_SEED.length} Einträge neu gesetzt`, version: TAXONOMY_VERSION });
    }

    // ── get_single: Einzelnen Eintrag per industry_id ────────────────────────
    if (action === 'get_single') {
      const { industry_id } = body;
      if (!industry_id) return Response.json({ error: 'industry_id fehlt', success: false }, { status: 400 });
      const entries = await base44.asServiceRole.entities.TaxonomyEntry.filter({ industry_id, is_active: true });
      if (!entries[0]) return Response.json({ error: 'Nicht gefunden', success: false }, { status: 404 });
      return Response.json({ success: true, profile: dbEntryToProfile(entries[0]) });
    }

    return Response.json({ error: 'Unbekannte Action', success: false }, { status: 400 });

  } catch (error) {
    console.error('[getTaxonomy] Error:', error?.message);
    return Response.json({ error: error?.message || 'Interner Fehler', success: false }, { status: 500 });
  }
});